### PR TITLE
add test-script for crfg curves

### LINKED ISSUE #273: TLS 1.3 ecdhe invalid parameters - crfg curves
* check if all-zero share in `key_share` is rejected with `illegal_parameter`
* check if key share of 1 is rejected with `illegal_parameter`
* check if too long and too short key share is rejected with `illegal_parameter`
* verify that `ec_point_formats` extension doesn't have impact on the negotiation

do the tests both for x25519 and x448 curve

### PR DESCRIPTION
**Pull request by NoName115**
### Description
New test-script for x25519 and x448 curves

### Motivation and Context
fixes #273 

### Checklist
- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [ ] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL
  - [x] NSS
  - [x] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

### Additional info
Travis CI will fail due to https://github.com/tomato42/tlslite-ng/pull/304

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/445)

### CODE REVIEW

**Comment by NoName115** [comment]
GnuTLS failed:
```
  'sanity x448 with compression ansiX962_compressed_char2'
  'sanity x448 with compression ansiX962_compressed_prime'
  'sanity x448 with compression uncompressed'
```
TlsFuzzer expected ServerHello msg but it recieved Alert(fatal, illegal_parameter).

Openssl is sending `decode_error` or `internal_error` when `illegal_parameter` alert is expected.

**Comment by tomato42** [comment]
gnutls does not support X448 as far as I can tell, so it looks like it's the [gnutls/gnutls#537](https://gitlab.com/gnutls/gnutls/issues/537) (it should have sent handshake_failure)

**Comment by NoName115** [comment]
NSS is sending `handshake_failure`, when `illegal_parameter` is expected, for x448 tests.

**Comment by tomato42** [comment]
NSS also doesn't support X448

**Comment by tomato42** [comment]
looks like it will have to wait for #457 to be merged

**Comment by tomato42** [comment]
Looks good, thanks!

**Pull request merged**
