### PR TITLE
Fixes to Signature Algorithms

### LINKED ISSUE #412: rsa_pss_pss signatures are accepted from rsaEncryption keys
# Bug Report

## System Information

| Type                     | Version/Name |
| ------------------------ | ------------ |
| Operating System Name    |  Fedora |
| Operating System Version |  26 |
| Python version           |  2.7.15|
| tlslite-ng version       | tlslite-ng-0.8.0-alpha13  |
| tlsfuzzer revision       |  24b634cde9a |

## Problem description

When checking the signature in CertificateVerify or ServerKeyExchange (in TLS1.2), tlsfuzzer will accept signatures that indicate use of rsassa-pss key, even if the server certificate has an `rsaEncryption` key

## Describe how to reproduce the problem

1. Configure the tlslite-ng server with rsaEncryption key in certificate
1. send client hello that advertises only rsa_pss_pss* signature schemes

## Expected behaviour

connection aborted with `handshake_alert`

## Include errors or backtraces

no backtraces, manual inspection

## Additional context

depends on https://github.com/tomato42/tlslite-ng/issues/279

### LINKED ISSUE #483: CVGenerator does not filter sig. alg based on used key
# Bug Report

## System Information

| Type                     | Version/Name |
| ------------------------ | ------------ |
| Operating System Name    | Fedora |
| Operating System Version | 27 |
| Python version           | 3.6.6 |
| tlslite-ng version       | 0.8.0a20 |
| tlsfuzzer revision       | 0f20be46ece202a8f46569030ead6616e9a667d1 |

## Problem description
CertificateVerifyGenerator class in messages.py does not filter signature schemes for `msg_alg` argument based on used key in a conversation. (E.g. now we can use rsa_pss_rsae_* sig. with rsa-pss key)

## Describe how to reproduce the problem

Steps to reproduce the behaviour:

1. run OpenSSL server
2. run `sanity` or `RSA-PSS only` test-case in `test-rsa-pss-sigs-on-certificate-verify.py` test-script with RSA-PSS key

## Expected behaviour

CV should select correct sig. scheme based on used key.

### PR DESCRIPTION
**Pull request by tomato42**
### Description

Fix bugs related to signature algorithm handling

### Motivation and Context

fixes #412 
fixes #483 
depends on https://github.com/tomato42/tlslite-ng/pull/337

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [ ] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - n/a
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/493)

### CODE REVIEW

**Comment by tomato42** [comment]
yes, this PR depends on tomato42/tlslite-ng#337

**Comment by tomato42** [comment]
waiving the codeclimate issue - we will rework and simplify CertificateVerifyGenerator when we will add support for ECDSA (and DSA) - will be easier to do when we know all requirements

**Comment by t8m** [comment]
OK, then.

**Comment by tomato42** [comment]
just additional test coverage added - merging without further review

**Pull request merged**
