### PR TITLE
new test-script for ssl3 legacy-version check

### LINKED ISSUE #372: SSL3 or earlier negotiation
# New test script idea

## What TLS message this idea relates to?

ClientHello `legacy_version`

## What is the behaviour the test script should test?

Verify that a TLS 1.3 ClientHello with `legacy_version` set to 0x0300 or earlier is rejected with `protocol_version` alert.

check 0x0000, 0x0200, 0x0002, 0x0100, 0x0103, 0x0102, 0x0001

the server should always reply with `protocol_version` alert

## Are there scripts that test related functionality?

`scripts/test-version-numbers.py`, `scripts/test-invalid-version.py`

## Additional information

verify that negotiation of SSL2 and SSL3 is disabled, that there is no version confusion between TLS and SSL

### PR DESCRIPTION
**Pull request by NoName115**
### Description

Verify that server reject connection with protocol_version alert for several invalid legacy versions.

### Motivation and Context

fixed #372 

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL
  - [x] NSS
  - [x] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/382)

### CODE REVIEW

**Comment by tomato42** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[scripts/test-legacy-version.py, line 1 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/382#-LCdBiNJD05ZVhWGI3O3:-LCdBiNJD05ZVhWGI3O4:b-mudsvw) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/9e830ad16c058ab3be04cf0a5fa5123bf122baa6/scripts/test-legacy-version.py#L1)):*
> ```Python
> # Author: Robert Kolcun, (c) 2015
> ```

date is wrong

---

*[scripts/test-legacy-version.py, line 75 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/382#-LCdC77HDNovBkyjLIq5:-LCdC77HDNovBkyjLIq6:bdwvuuv) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/9e830ad16c058ab3be04cf0a5fa5123bf122baa6/scripts/test-legacy-version.py#L75)):*
> ```Python
>     ciphers = [CipherSuite.TLS_RSA_WITH_AES_128_CBC_SHA,
>                CipherSuite.TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
>     node = node.add_child(ClientHelloGenerator(ciphers))
> ```

sorry, the issue was not precise enough, the test should send a TLS 1.3 client hello with a wrong version, not a TLS 1.2/TLS 1.0 client hello with wrong version

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/382)*

**Comment by tomato42** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/tomato42/tlsfuzzer/382#-LCdCg3F6vnxykRSjb81:-LCdCg3F6vnxykRSjb82:b-g157q5) (no related file):*
the script should also be renamed to `test-tls13-legacy-version.py`

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/382)*

**Comment by tomato42** [comment]
Reviewed 4 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[scripts/test-legacy-version.py, line 142 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/382#-LCi56swDP3p3Hbkr1Td:-LCi56swDP3p3Hbkr1Te:b-uw2hih) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/9e830ad16c058ab3be04cf0a5fa5123bf122baa6/scripts/test-legacy-version.py#L142)):*
> ```Python
>             bad += 1
>             failed.append(c_name)
> ```

test description and version report missing, please add

---

*[scripts/test-tls13-legacy-version.py, line 130 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/382#-LCi4_LZAZS5RTse5bRg:-LCi4_L_E1qiPcdAOqnr:bre2j17) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/577d410385e62d77693d3b9b943a69a06a7c270c/scripts/test-tls13-legacy-version.py#L130)):*
> ```Python
>         node = node.add_child(ExpectAlert(description=AlertDescription.protocol_version))
>         node = node.add_child(ExpectClose())
>         conversations['version {0}'.format(str(prot_version))] = conversation
> ```

FYI: we use format exactly so that explicitly using `str()` is not necessary

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/382)*

**Comment by tomato42** [comment]
Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/382)*

**Comment by tomato42** [comment]
@NoName115 please make a comment when you rebase patches, I don't get notifications unless there are new patches added or comments made

**Comment by NoName115** [comment]
I added TLS 1.3 draft, but now all tests against openssl are failing.
Openssl send Handshake(server_hello) message.

**Comment by tomato42** [comment]
thanks!

**Pull request merged**
