### PR TITLE
Issue 212 tls13 finished fuzzing

### LINKED ISSUE #212: TLS 1.3 Finished fuzzing
- verify that server sends a correct Finished message
- verify that server will reject a Finished message that has a single bit error on any position
- verify that server will reject a Finished message that has value that is truncated (either left- or righ-truncated) by one byte (or more)
  - especially SHA-384 PRF to SHA-256 size
  - or to 12 bytes (as it was in TLS 1.2)
- verify that server will reject a Finished message value that is padded (either left- or right-padded) by one or more bytes (especially to the size of SHA-384 PRF for SHA-256 ciphers)
- verify that server will reject completely empty Finished message
- verify that the above holds both for SHA-256 and SHA-384 PRF ciphers

### PR DESCRIPTION
**Pull request by ep69**
### Description

Fuzzing Finished message according to #212 specification.

### Motivation and Context

fixes #212 

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [ ] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL
  - [x] NSS
  - [ ] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/411)

### CODE REVIEW

**Comment by tomato42** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed, 11 unresolved discussions (waiting on @ep69)

---

*[a discussion](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFX_hzu2fk1rR4iJARZ:-LFX_hzu2fk1rR4iJAR_:burdloq) (no related file):*
unit tests for changes in `messages.py` missing

---

*[scripts/test-tls13-finished.py, line 91 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXXnAy-Zr3aAz_LudI:-LFXXnAz7dvPhgVpP6z3:bjyvget) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L91)):*
> ```Python
>     ext[ExtensionType.key_share] = ClientKeyShareExtension().create(key_shares)
>     ext[ExtensionType.supported_versions] = SupportedVersionsExtension()\
>         .create([(3, 3), TLS_1_3_DRAFT])
> ```

reversed order, won't interoperate with GnuTLS

---

*[scripts/test-tls13-finished.py, line 108 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXXuk_EyC7ZFR9l8L-:-LFXXuka5v-C45RiO738:b-7x715l) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L108)):*
> ```Python
>     node = node.add_child(ApplicationDataGenerator(
>         bytearray(b"GET / HTTP/1.0\r\n\r\n")))
>     node = node.add_child(ExpectNewSessionTicket())
> ```

NewSessionTicket is optional and can be sent multiple times, use the code from current tls13-conversation to expect this behaviour

---

*[scripts/test-tls13-finished.py, line 131 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXXhvD5aJ3bPGWc-r-:-LFXXhvD5aJ3bPGWc-r0:bjyvget) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L131)):*
> ```Python
>         ext[ExtensionType.key_share] = ClientKeyShareExtension().create(key_shares)
>         ext[ExtensionType.supported_versions] = SupportedVersionsExtension()\
>             .create([(3, 3), TLS_1_3_DRAFT])
> ```

reversed order, won't interoperate with GnuTLS

---

*[scripts/test-tls13-finished.py, line 137 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXXM5A7Q7d0PpytTaO:-LFXXM5A7Q7d0PpytTaP:b51t7d1) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L137)):*
> ```Python
>                     SignatureScheme.rsa_pss_pss_sha256,
>                     SignatureScheme.rsa_pss_rsae_sha384,
>                     SignatureScheme.rsa_pss_pss_sha384]
> ```

why this larger list of signature algorithms here but not in sanity case?

---

*[scripts/test-tls13-finished.py, line 151 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXYC-s0cMYrkHI60n0:-LFXYC-s0cMYrkHI60n1:bsa6zs4) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L151)):*
> ```Python
> 
>         # we do not expect any application data back
>         # after malforming the Finished message
> ```

actually, the server may send a NewSessionTicket now, even before our Finished was sent (if it didn't ask for client authentication)

---

*[scripts/test-tls13-finished.py, line 210 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXZHiH4GEgRtQIokBb:-LFXZHiH4GEgRtQIokBc:b-7ncvap) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L210)):*
> ```Python
>                  (CipherSuite.TLS_AES_128_GCM_SHA256, 0,  -16),
>                  (CipherSuite.TLS_AES_128_GCM_SHA256, 0,  -32),
>                  (CipherSuite.TLS_AES_128_GCM_SHA256, 0,  12),
> ```

I'm assuming this is the truncation to size of TLS1.2 Finished while the other ones are to some arbitrary sizes?

---

*[scripts/test-tls13-finished.py, line 223 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXZZ1X1zQS5uamOe8U:-LFXZZ1X1zQS5uamOe8V:b-f84tlh) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L223)):*
> ```Python
>                  (CipherSuite.TLS_AES_256_GCM_SHA384, 0,  -16),
>                  (CipherSuite.TLS_AES_256_GCM_SHA384, 0,  -32),
>                  (CipherSuite.TLS_AES_256_GCM_SHA384, 0,  12),
> ```

which one of those will truncate it to the size of SHA256? maybe add comments that mark those special values?

---

*[scripts/test-tls13-finished.py, line 262 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXZkgD9nWduvRFAK3a:-LFXZkgD9nWduvRFAK3b:bq8qc3b) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L262)):*
> ```Python
> 
>         # we do not expect any application data back
>         # after malforming the Finished message
> ```

again, NewSessionTicket can be sent early here

---

*[scripts/test-tls13-finished.py, line 276 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFX_1aO3Ipbxw88KT2t:-LFX_1aO3Ipbxw88KT2u:b-fotaep) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L276)):*
> ```Python
>                  (CipherSuite.TLS_AES_128_GCM_SHA256, 0, 0, 4),
>                  (CipherSuite.TLS_AES_128_GCM_SHA256, 0, 0, 8),
>                  (CipherSuite.TLS_AES_128_GCM_SHA256, 0, 0, 16),
> ```

maybe mark it as a value that pads it to the size of SHA384?

---

*[tlsfuzzer/messages.py, line 947 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFX_VIA0yKKIduuGb4I:-LFX_VIA0yKKIduuGb4J:bo43zfz) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/tlsfuzzer/messages.py#L947)):*
> ```Python
>         # messing with the message - padding
>         verify_data = bytearray([self.pad_byte]*self.pad_left) \
>                     + verify_data \
> ```

nit: this is over indented, the indent should be four spaces

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/411)*

**Comment by ep69** [comment]
Review status: 2 of 5 files reviewed, 11 unresolved discussions (waiting on @tomato42 and @ep69)

---

*[a discussion](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFX_hzu2fk1rR4iJARZ:-LFXrf71-1h-VbALFY37:b-896fix) (no related file):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

unit tests for changes in `messages.py` missing
</blockquote></details>

Done.

---

*[scripts/test-tls13-finished.py, line 91 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXXnAy-Zr3aAz_LudI:-LFXeMVx4E4OLdHPkwHB:b-896fix) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L91)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

reversed order, won't interoperate with GnuTLS
</blockquote></details>

Done.

---

*[scripts/test-tls13-finished.py, line 108 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXXuk_EyC7ZFR9l8L-:-LFXeequ6RWJrj52BDdI:b-iuk6fv) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L108)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

NewSessionTicket is optional and can be sent multiple times, use the code from current tls13-conversation to expect this behaviour
</blockquote></details>

Done.kkkkkkjjkkkjkj

---

*[scripts/test-tls13-finished.py, line 131 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXXhvD5aJ3bPGWc-r-:-LFXew8cCCZyd_sV5Gxs:b-896fix) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L131)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

reversed order, won't interoperate with GnuTLS
</blockquote></details>

Done.

---

*[scripts/test-tls13-finished.py, line 137 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXXM5A7Q7d0PpytTaO:-LFXgPk7EA5Mq-txKJSs:b-896fix) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L137)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why this larger list of signature algorithms here but not in sanity case?
</blockquote></details>

Done.

---

*[scripts/test-tls13-finished.py, line 151 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXYC-s0cMYrkHI60n0:-LFXk1gN6nFja2mQ_53I:b-896fix) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L151)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

actually, the server may send a NewSessionTicket now, even before our Finished was sent (if it didn't ask for client authentication)
</blockquote></details>

Done.

---

*[scripts/test-tls13-finished.py, line 210 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXZHiH4GEgRtQIokBb:-LFXgnn-7tYsEcoWGwJO:b-iexgoo) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L210)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

I'm assuming this is the truncation to size of TLS1.2 Finished while the other ones are to some arbitrary sizes?
</blockquote></details>

yes, will add comment

---

*[scripts/test-tls13-finished.py, line 223 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXZZ1X1zQS5uamOe8U:-LFXi6Ye7o_6HtEe2eN9:bb7f2mf) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L223)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

which one of those will truncate it to the size of SHA256? maybe add comments that mark those special values?
</blockquote></details>

done

---

*[scripts/test-tls13-finished.py, line 262 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFXZkgD9nWduvRFAK3a:-LFXlERS-bZf71QczoTo:b-896fix) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L262)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

again, NewSessionTicket can be sent early here
</blockquote></details>

Done.

---

*[scripts/test-tls13-finished.py, line 276 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFX_1aO3Ipbxw88KT2t:-LFXjDFJ1fqDd5TQujvl:b-896fix) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/scripts/test-tls13-finished.py#L276)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

maybe mark it as a value that pads it to the size of SHA384?
</blockquote></details>

Done.

---

*[tlsfuzzer/messages.py, line 947 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFX_VIA0yKKIduuGb4I:-LFXjXcE4zCUPExeKvnr:b-n9tkhd) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bb2295ebaf71f96260c77622a7071dd9a4dc6361/tlsfuzzer/messages.py#L947)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

nit: this is over indented, the indent should be four spaces
</blockquote></details>

changed

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/411)*

**Comment by ep69** [comment]
GnuTLS could not have been reasonably tested because of existing bug.

**Comment by tomato42** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @tomato42)

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/411)*

**Comment by tomato42** [comment]
travis blocked by https://github.com/tomato42/tlslite-ng/pull/276

**Comment by tomato42** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/411)*

**Comment by ep69** [comment]
Review status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @tomato42)

---

*[scripts/test-tls13-finished.py, line 176 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LFr6ZsU25S-OfFE2KSa:-LFrRgNP7kNWx0lyFa-2:b-896fix) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/7c1c63707934e6a8b7a551cf3d72689e40f51fab/scripts/test-tls13-finished.py#L176)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

> ```python
> num_limit/2
> ```

that will give float in python3, which is an invalid input for the `random.sample()` method
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/411)*

**Comment by tomato42** [comment]
Reviewed 1 of 6 files at r4, 5 of 5 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[scripts/test-tls13-finished.py, line 384 at r5](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LG05LUT84xIfIJ_YCVd:-LG05LUT84xIfIJ_YCVe:b6bzk5a) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bcae0b60a141f199ef5292a44e622a18a3dfe2d9/scripts/test-tls13-finished.py#L384)):*
> ```Python
> 
>         # This message may be sent right after server finished
>         cycle = ExpectNewSessionTicket()
> ```

btw, I wonder how this sibling to Finished will work with New Session Ticket...

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/411)*

**Comment by ep69** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[scripts/test-tls13-finished.py, line 384 at r5](https://reviewable.io/reviews/tomato42/tlsfuzzer/411#-LG05LUT84xIfIJ_YCVd:-LG0DFok-cm4cTCKEONT:b-h3zov8) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bcae0b60a141f199ef5292a44e622a18a3dfe2d9/scripts/test-tls13-finished.py#L384)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

btw, I wonder how this sibling to Finished will work with New Session Ticket...
</blockquote></details>

We will see ;)

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/411)*

**Comment by tomato42** [comment]
Reviewed 5 of 5 files at r7.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/411)*

**Comment by tomato42** [comment]
@ep69 thanks!

**Pull request merged**
