### PR TITLE
test-script for specific number of SessionTickets

### LINKED ISSUE #394: Counting TLS 1.3 New Session Tickets
# New test script idea

## What TLS message this idea relates to?

NewSessionTicket

## What is the behaviour the test script should test?

Current scripts accept any number of NewSessionTicket, including none; for some configurations that can be a bug.
Create a script that expect a very specific number of NST messages right after server Finished, aborts in case the server did sent too few or too many tickets. That should be parametrised by command line switch

## Are there scripts that test related functionality?

`scripts/test-tls13-conversation.py`

### PR DESCRIPTION
**Pull request by NoName115**
### Description
New test script expect specific number of NewSessionTickets, which can be specified by input argument "-t num" with number of these tickets.

### Motivation and Context
fixes #394 

### Checklist
- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL
  - [x] NSS
  - [x] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/416)

### CODE REVIEW

**Comment by NoName115** [comment]
I have question to this issue, i rewrite sanity test in which the number of tickets can be specified.
Or sanity check should be same as test-tls13-conversation.py and then create test for specific number of tickets?

**Comment by tomato42** [comment]
I'd say that the sanity check  should be the same as in tls13-conversation - i.e. any number of tickets should be acceptable

**Comment by tomato42** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed, 3 unresolved discussions (waiting on @NoName115)

---

*[scripts/test-tls13-count-tickets.py, line 1 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/416#-LG02dBpEvPCo5M2rKBc:-LG02dBq-DbCyiDtpvEQ:bh6hlkf) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/211ea39e3523d98bc16e03963f70856468152ef7/scripts/test-tls13-count-tickets.py#L1)):*
> ```Python
> # Author: Hubert Kario, (c) 2018
> ```

wrong copyright

---

*[scripts/test-tls13-count-tickets.py, line 110 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/416#-LG03AnN8ur3mogq4Abi:-LG03AnN8ur3mogq4Abj:b-h3q1ik) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/211ea39e3523d98bc16e03963f70856468152ef7/scripts/test-tls13-count-tickets.py#L110)):*
> ```Python
>         bytearray(b"GET / HTTP/1.0\r\n\r\n")))
> 
>     for i in range(0, num_tickets):
> ```

when lower value of range is 0, it can be omitted: `range(num_tickets)` will work fine

---

*[scripts/test-tls13-count-tickets.py, line 111 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/416#-LG02wUS44pG4e5kXIsj:-LG02wUS44pG4e5kXIsk:b-w24ssi) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/211ea39e3523d98bc16e03963f70856468152ef7/scripts/test-tls13-count-tickets.py#L111)):*
> ```Python
> 
>     for i in range(0, num_tickets):
>         node = node.add_child(ExpectNewSessionTicket())
> ```

it should check for NewSessionTicket right after sending Finished, but before sending Application Data

also, this is the counting test case, while it's named sanity...

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/416)*

**Comment by NoName115** [comment]
Fixed and rebased.

**Comment by NoName115** [comment]
Done.

**Comment by tomato42** [comment]
perfect, thank you!

**Pull request merged**
