### PR TITLE
Update test-cases with rsa-pss

### LINKED ISSUE #449: Update test cases with RSA-PSS to draft-28
# Bug Report
Test cases like `test-sig-algs.py`, `test-certificate-request.py` and `test-rsa-pss-sigs-on-certificate-verify.py` were written when the rsa-pss support did not differentiate between rsa-pss signatures made with rsaEncryption keys and rsa-pss keys.
They need to be updated, as the expected behaviour depending on the key used, is very different.

## System Information

| Type                     | Version/Name |
| ------------------------ | ------------ |
| Operating System Name    |  Fedora |
| Operating System Version |  27|
| Python version           |  3.6.6 |
| tlslite-ng version       |  bad2b98b2c382674f7 |
| tlsfuzzer revision       |  ff968e7ae74ad0319 |

## Problem description

Test cases do not detect if the used key is is of rsaEncryption or rsa-pss type and don't behave differently based on that.
In effect, conversations which are marked `sanity` will create malformed messages

## Describe how to reproduce the problem

start TLS 1.2 server that asks for client certificates
run `test-rsa-pss-sigs-on-certificate-verify.py` with rsa-pss client key

## Expected behaviour

RFC mandated behaviour

## Include errors or backtraces

`sanity` fails because CertificateVerify used rsa_pss_rsae_sha256 signature with rsa-pss key

### PR DESCRIPTION
**Pull request by NoName115**
### Description
Test-cases `test-sig-algs.py`, `test-certificate-request.py` and `test-rsa-pss-sigs-on-certificate-verify.py` are updated with rsa-pss sig algs.
And RSA-PSS Cert & Key for client is added.

### Motivation and Context
fixes #449 

### Checklist
- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [ ] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL
  - [x] NSS
  - [x] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/470)

### CODE REVIEW

**Comment by NoName115** [comment]
One test in tlslite-ng is failing, `rsa_pkcs1_sha256 signature in CertificateVerify with rsa-pss key`
```
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7f6f970f4b38> (child: <tlsfuzzer.expect.ExpectClose object at 0x7f6f970f4ba8>) with last message being: <tlslite.messages.Message object at 0x7f6f970f7f28>

AssertionError: Unexpected message from peer: ChangeCipherSpec()
```

**Comment by NoName115** [comment]
> is it because the server is sending two CCS messages? Isn't the test case about client's CertificateVerify?

So what's the correct behaviour? As i tested it with openssl and gnutls, both implementations sent AlertMessage but with incorrect AlertDescription, (`internal_error` for GnuTLS & `illegal_parameter` for OpenSSL), we expect `decrypt_error`.

**Comment by tomato42** [comment]
rsa_pkcs1* signatures can never be made with rsa-pss keys, so tlslite-ng not rejecting them is a bug: https://github.com/tomato42/tlslite-ng/issues/279

`internal_error` from GnuTLS is definitely wrong, if it should be `illegal_parameter` or `decrypt_error` depends if the TLS layer should know the type of key used, if yes then `illegal_parameter` is correct, if not then `decrypt_error` (as the error then comes from the crypto library) – I think we should add a switch to allow either behaviour (as long as it is consistent between rsa_pkcs1_* and rsa-pss-rsae signatures made with rsa-pss keys)

**Comment by NoName115** [comment]
Rebased.

I added support for illegal_parameter as a description for Alert Message, but there is a problem with OpenSSL.
In case when client use rsaEncryption, OpenSSL sent `decrypt_error` for all tests with rsa_pss_rsae_* sigs, that is expected.
But it sent `illegal_parameter` for `rsa_pss_pss_* in CertificateVerify with incorrect salt len` tests, and for `rsa_pss_pss_* in CertificateVerify` tlsfuzzer ended with
```
Error encountered while processing node <tlsfuzzer.expect.ExpectChangeCipherSpec object at 0x7f9fc8ae2400> (child: <tlsfuzzer.expect.ExpectFinished object at 0x7f9fc8ae2438>) with last message being: <tlslite.messages.Message object at 0x7f9fc7d59710>
...
Unexpected message from peer: Alert(fatal, illegal_parameter)
```

For client with RSA-PSS, `sanity`, `rsa_pss_rsae_* in CV`, `RSA-PSS only` ended with
```
Error encountered while processing node <tlsfuzzer.expect.ExpectChangeCipherSpec object at 0x7fface06b0f0> (child: <tlsfuzzer.expect.ExpectFinished object at 0x7fface06b128>) with last message being: <tlslite.messages.Message object at 0x7ffacd5679e8>
...
AssertionError: Unexpected message from peer: Alert(fatal, illegal_parameter)
```
And `malformed`, `  short sig with rsa_pss_rsae_sha256 id` and `rsa_pss_rsae_* in CertificateVerify with incorrect salt len` tests, ended with wrong alert description (`decrypt` expected, `illegal_par` recieved).

I think that we can handle all the cases when OpenSSL sends `decrypt` or `illegal_p` but it will be more complicated as we need to check for client certificate type, if support for illegal_parameter is used and check the type of sig.

**GnuTLS**
Sent `internal_error` as in the comment above. But the `sanity` and `RSA-PSS only` tests failed with
```
Error encountered while processing node <tlsfuzzer.messages.FinishedGenerator object at 0x7f26098d71d0> (child: <tlsfuzzer.expect.ExpectChangeCipherSpec object at 0x7f26098d7080>) with last message being: <tlslite.messages.Finished object at 0x7f2608dd5ac8>
...
AssertionError: Unexpected closure from peer
```
<details><summary>GnuTLS output</summary>

```
* Accepted connection from IPv4 127.0.0.1 port 40754 on Mon Nov  5 16:14:37 2018
|<5>| REC[0x13657f0]: Allocating epoch #1
|<3>| ASSERT: buffers.c[get_last_packet]:1171
|<5>| REC[0x13657f0]: SSL 3.0 Handshake packet received. Epoch 0, length: 109
|<5>| REC[0x13657f0]: Expected Packet Handshake(22)
|<5>| REC[0x13657f0]: Received Packet Handshake(22) with length: 109
|<5>| REC[0x13657f0]: Decrypted Packet[0] Handshake(22) with length: 109
|<4>| HSK[0x13657f0]: CLIENT HELLO (1) was received. Length 105[105], frag offset 0, frag length: 105, sequence: 0
|<4>| HSK[0x13657f0]: Client's version: 3.3
|<3>| ASSERT: db.c[_gnutls_server_restore_session]:298
|<4>| EXT[0x13657f0]: Parsing extension 'Signature Algorithms/13' (24 bytes)
|<4>| EXT[0x13657f0]: rcvd signature algo (8.4) RSA-PSS-RSAE-SHA256
|<4>| EXT[0x13657f0]: rcvd signature algo (8.5) RSA-PSS-RSAE-SHA384
|<4>| EXT[0x13657f0]: rcvd signature algo (8.6) RSA-PSS-RSAE-SHA512
|<4>| EXT[0x13657f0]: rcvd signature algo (8.9) RSA-PSS-SHA256
|<4>| EXT[0x13657f0]: rcvd signature algo (8.10) RSA-PSS-SHA384
|<4>| EXT[0x13657f0]: rcvd signature algo (8.11) RSA-PSS-SHA512
|<4>| EXT[0x13657f0]: rcvd signature algo (6.1) RSA-SHA512
|<4>| EXT[0x13657f0]: rcvd signature algo (5.1) RSA-SHA384
|<4>| EXT[0x13657f0]: rcvd signature algo (4.1) RSA-SHA256
|<4>| EXT[0x13657f0]: rcvd signature algo (3.1) (null)
|<4>| EXT[0x13657f0]: rcvd signature algo (2.1) RSA-SHA1
|<4>| HSK[0x13657f0]: Received safe renegotiation CS
|<2>| checking c0.13 (GNUTLS_ECDHE_RSA_AES_128_CBC_SHA1) for compatibility
|<3>| ASSERT: server_name.c[gnutls_server_name_get]:235
|<4>| HSK[0x13657f0]: Requested server name: ''
|<4>| HSK[0x13657f0]: checking compat of GNUTLS_ECDHE_RSA_AES_128_CBC_SHA1 with certificate[3] (RSA-PSS/X.509)
|<4>| checking cert compat with RSA-PSS-RSAE-SHA256
|<4>| checking cert compat with RSA-PSS-RSAE-SHA384
|<4>| checking cert compat with RSA-PSS-RSAE-SHA512
|<4>| checking cert compat with RSA-PSS-SHA256
|<4>| Selected signature algorithm: RSA-PSS-SHA256
|<2>| Selected (RSA-PSS) cert based on ciphersuite c0.13: GNUTLS_ECDHE_RSA_AES_128_CBC_SHA1
|<4>| HSK[0x13657f0]: Selected group SECP256R1 (2)
|<4>| HSK[0x13657f0]: Selected cipher suite: GNUTLS_ECDHE_RSA_AES_128_CBC_SHA1
|<4>| HSK[0x13657f0]: Selected version TLS1.2
|<4>| HSK[0x13657f0]: Safe renegotiation succeeded
|<4>| HSK[0x13657f0]: SessionID: 1bde5b1722eb2deeeaa69e01d718adcc48c64ac2f81610f00f688825d14bb1e0
|<4>| EXT[0x13657f0]: Preparing extension (Maximum Record Size/1) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Preparing extension (OCSP Status Request/5) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Preparing extension (Client Certificate Type/19) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Preparing extension (Server Certificate Type/20) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Preparing extension (Supported Groups/10) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Preparing extension (Supported EC Point Formats/11) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Not sending extension (SRP/12) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Not sending extension (Signature Algorithms/13) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Preparing extension (SRTP/14) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Preparing extension (Heartbeat/15) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Preparing extension (ALPN/16) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Preparing extension (Encrypt-then-MAC/22) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Preparing extension (Extended Master Secret/23) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Preparing extension (Session Ticket/35) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Not sending extension (Key Share/51) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Preparing extension (Supported Versions/43) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Not sending extension (Post Handshake Auth/49) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Preparing extension (Safe Renegotiation/65281) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Sending extension Safe Renegotiation/65281 (1 bytes)
|<4>| EXT[0x13657f0]: Preparing extension (Server Name Indication/0) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Not sending extension (Cookie/44) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Not sending extension (Early Data/42) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Not sending extension (PSK Key Exchange Modes/45) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Preparing extension (Record Size Limit/28) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Not sending extension (ClientHello Padding/21) for 'TLS 1.2 server hello'
|<4>| EXT[0x13657f0]: Not sending extension (Pre Shared Key/41) for 'TLS 1.2 server hello'
|<4>| HSK[0x13657f0]: SERVER HELLO was queued [81 bytes]
|<4>| HSK[0x13657f0]: CERTIFICATE was queued [871 bytes]
|<4>| HSK[0x13657f0]: signing TLS 1.2 handshake data: using RSA-PSS-SHA256
|<3>| ASSERT: mpi.c[wrap_nettle_mpi_print]:60
|<4>| HSK[0x13657f0]: SERVER KEY EXCHANGE was queued [333 bytes]
|<4>| EXT[0x13657f0]: sent signature algo (4.1) RSA-SHA256
|<4>| EXT[0x13657f0]: sent signature algo (8.9) RSA-PSS-SHA256
|<4>| EXT[0x13657f0]: sent signature algo (8.4) RSA-PSS-RSAE-SHA256
|<4>| EXT[0x13657f0]: sent signature algo (4.3) ECDSA-SHA256
|<4>| EXT[0x13657f0]: sent signature algo (8.7) EdDSA-Ed25519
|<4>| EXT[0x13657f0]: sent signature algo (5.1) RSA-SHA384
|<4>| EXT[0x13657f0]: sent signature algo (8.10) RSA-PSS-SHA384
|<4>| EXT[0x13657f0]: sent signature algo (8.5) RSA-PSS-RSAE-SHA384
|<4>| EXT[0x13657f0]: sent signature algo (5.3) ECDSA-SHA384
|<4>| EXT[0x13657f0]: sent signature algo (6.1) RSA-SHA512
|<4>| EXT[0x13657f0]: sent signature algo (8.11) RSA-PSS-SHA512
|<4>| EXT[0x13657f0]: sent signature algo (8.6) RSA-PSS-RSAE-SHA512
|<4>| EXT[0x13657f0]: sent signature algo (6.3) ECDSA-SHA512
|<4>| EXT[0x13657f0]: sent signature algo (2.1) RSA-SHA1
|<4>| EXT[0x13657f0]: sent signature algo (2.3) ECDSA-SHA1
|<4>| HSK[0x13657f0]: CERTIFICATE REQUEST was queued [71 bytes]
|<4>| HSK[0x13657f0]: SERVER HELLO DONE was queued [4 bytes]
|<5>| REC[0x13657f0]: Preparing Packet Handshake(22) with length: 81 and min pad: 0
|<5>| REC[0x13657f0]: Sent Packet[1] Handshake(22) in epoch 0 and length: 86
|<5>| REC[0x13657f0]: Preparing Packet Handshake(22) with length: 871 and min pad: 0
|<5>| REC[0x13657f0]: Sent Packet[2] Handshake(22) in epoch 0 and length: 876
|<5>| REC[0x13657f0]: Preparing Packet Handshake(22) with length: 333 and min pad: 0
|<5>| REC[0x13657f0]: Sent Packet[3] Handshake(22) in epoch 0 and length: 338
|<5>| REC[0x13657f0]: Preparing Packet Handshake(22) with length: 71 and min pad: 0
|<5>| REC[0x13657f0]: Sent Packet[4] Handshake(22) in epoch 0 and length: 76
|<5>| REC[0x13657f0]: Preparing Packet Handshake(22) with length: 4 and min pad: 0
|<5>| REC[0x13657f0]: Sent Packet[5] Handshake(22) in epoch 0 and length: 9
|<3>| ASSERT: buffers.c[get_last_packet]:1171
|<5>| REC[0x13657f0]: SSL 3.3 Handshake packet received. Epoch 0, length: 887
|<5>| REC[0x13657f0]: Expected Packet Handshake(22)
|<5>| REC[0x13657f0]: Received Packet Handshake(22) with length: 887
|<5>| REC[0x13657f0]: Decrypted Packet[1] Handshake(22) with length: 887
|<4>| HSK[0x13657f0]: CERTIFICATE (11) was received. Length 883[883], frag offset 0, frag length: 883, sequence: 0
- Peer's certificate was NOT verified.
|<3>| ASSERT: buffers.c[get_last_packet]:1171
|<5>| REC[0x13657f0]: SSL 3.3 Handshake packet received. Epoch 0, length: 70
|<5>| REC[0x13657f0]: Expected Packet Handshake(22)
|<5>| REC[0x13657f0]: Received Packet Handshake(22) with length: 70
|<5>| REC[0x13657f0]: Decrypted Packet[2] Handshake(22) with length: 70
|<4>| HSK[0x13657f0]: CLIENT KEY EXCHANGE (16) was received. Length 66[66], frag offset 0, frag length: 66, sequence: 0
|<3>| ASSERT: buffers.c[get_last_packet]:1171
|<5>| REC[0x13657f0]: SSL 3.3 Handshake packet received. Epoch 0, length: 264
|<5>| REC[0x13657f0]: Expected Packet Handshake(22)
|<5>| REC[0x13657f0]: Received Packet Handshake(22) with length: 264
|<5>| REC[0x13657f0]: Decrypted Packet[3] Handshake(22) with length: 264
|<4>| HSK[0x13657f0]: CERTIFICATE VERIFY (15) was received. Length 260[260], frag offset 0, frag length: 260, sequence: 0
|<4>| HSK[0x13657f0]: verify cert vrfy: using RSA-SHA256
|<4>| have key: RSA-PSS/6, with sign RSA-SHA256/6
|<3>| ASSERT: pubkey.c[pubkey_supports_sig]:1908
|<3>| ASSERT: pubkey.c[gnutls_pubkey_verify_data2]:1764
|<3>| ASSERT: tls-sig.c[_gnutls_handshake_verify_crt_vrfy12]:373
|<3>| ASSERT: cert.c[_gnutls_proc_cert_client_crt_vrfy]:1052
|<3>| ASSERT: handshake.c[handshake_server]:3425
Error in handshake: The signature is incompatible with the public key.
|<5>| REC: Sending Alert[2|80] - Internal error
|<5>| REC[0x13657f0]: Preparing Packet Alert(21) with length: 2 and min pad: 0
|<5>| REC[0x13657f0]: Sent Packet[6] Alert(21) in epoch 0 and length: 7
|<5>| REC[0x13657f0]: Start of epoch cleanup
|<5>| REC[0x13657f0]: End of epoch cleanup
|<5>| REC[0x13657f0]: Epoch #0 freed
|<5>| REC[0x13657f0]: Epoch #1 freed
```


</details>

**Comment by tomato42** [comment]
but the expected behaviour is different depending if the key used is rsaEncryption or rsassa-Pss; which keys were used in those tests above?

**Comment by NoName115** [comment]
sorry, for GnuTLS i used RSA-PSS on a client side.

**Comment by NoName115** [comment]
For OpenSSL i used
```
# localhost is rsaEncryption
./apps/openssl s_server -Verify 1 -www -key ../localhost.key -cert ../localhost.crt
```
and for GnuTLS:
```
./gnutls-http-serv --priority NORMAL:-VERS-ALL:+VERS-TLS1.3:+VERS-TLS1.2:+DHE-PSK:+PSK -p 4433 -d 6 --require-client-cert
```

**Comment by NoName115** [comment]
Fixed.

**tlslite-ng**
For rsaEncryption, new 3 negative tests `rsa_pss_pss_* in CV` failed with
```
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7f327fa16fd0> (child: <tlsfuzzer.expect.ExpectClose object at 0x7f327fa1c080>) with last message being: <tlslite.messages.Message object at 0x7f327ef07da0>
...
AssertionError: Unexpected message from peer: ChangeCipherSpec()
```
For RSA-PSS, same 3 negative tests failed (`rsa_pss_rsae_* in CV`) with same error message.
And `  'rsa_pkcs1_sha256 signature in CertificateVerify with rsa-pss key'` failed with same error message as tests above.

**OpenSSL**
For RSA-PSS, `sanity`, `RSA-PSS only` failed with:
```
Error encountered while processing node <tlsfuzzer.expect.ExpectChangeCipherSpec object at 0x7f98616be080> (child: <tlsfuzzer.expect.ExpectFinished object at 0x7f98616be208>) with last message being: <tlslite.messages.Message object at 0x7f9860bb9240>
...
AssertionError: Unexpected message from peer: Alert(fatal, illegal_parameter)
```

**GnuTLS**
For rsaEncryption new 3 negative tests failed with a same error message as for tlslite-ng.
And RSA-PSS, same 3 negative tests failed with same error message. And `sanity`, `RSA-PSS only` failed with a error message described in my previous comment.

**Comment by NoName115** [comment]
Fixed.

**Comment by NoName115** [comment]
Done.

**Comment by NoName115** [comment]
Fixed.
I waived that failures in json files.

**Comment by tomato42** [comment]
Thank you!

**Comment by NoName115** [comment]
Thanks for reviews!

**Pull request merged**
