### PR TITLE
test TLS 1.3 version negotiation

### LINKED ISSUE #203: TLS 1.3 version negotiation
Verify that if the Client Hello versions extension doesn't include TLS 1.3 version (but does include, say, TLS 1.4, or past draft versions, with all the necessary extensions) TLS 1.3 is not negotiated.

Verify that supported_versions were not sent in ServerHello when negotiating TLS 1.2

Check if `supported_versions` can be used to negotiate TLS 1.1 even if TLS 1.2 is enabled on the server.

Check if when older protocols are disabled on server, and `supported_versions` lists only them, the connection is aborted with `protocol_version`.

Check if `legacy_version` in TLS 1.3 ClientHello is set to higher value than 0x0303, TLS 1.2 is negotiated.

Verify that `legacy_record_version` from plaintext records with ClientHello are ignored and can be set to any valude with 0x03 on first byte (in particular, both 0x0301 and 0x0303 must work)

Verify that TLS 1.3 cannot be negotiated using SSLv2-style ClientHello message (that server picks TLS 1.2 in such case).

(see also: #244, #348 )

### PR DESCRIPTION
**Pull request by nmav**
### Description

Introduces TLS 1.3 tests for version negotiation from #203 issue

Resolves #203

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
  - The following fail under tlslite:
    - 'fallback from TLS 1.10 to 1.1'
    - 'SSL 3.0 in supported version'
    - 'tls 1.10 only'
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL (succeeds)
  - [x] NSS
  - [x] GnuTLS (succeeds)
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/380)

### CODE REVIEW

**Comment by tomato42** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[scripts/test-tls13-version-negotiation.py, line 147 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCdARN19L1B8VVYuZ7q:-LCdARN19L1B8VVYuZ7r:brvx7bv) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/0e2b6a49e3a7afde7895bcc654d56930e458007b/scripts/test-tls13-version-negotiation.py#L147)):*
> ```Python
> 	node = node.add_child(ExpectApplicationData())
> 	node = node.add_child(AlertGenerator(AlertLevel.warning,
> 					 AlertDescription.close_notify))
> ```

tabs instead of spaces

---

*[tests/tlslite-ng.json, line 75 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCdAY_HEgNDiVbIjT_Q:-LCdAY_HEgNDiVbIjT_R:b-u1h438) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/0e2b6a49e3a7afde7895bcc654d56930e458007b/tests/tlslite-ng.json#L75)):*
> ```JSON
>          {"name" : "test-dhe-rsa-key-exchange-signatures.py"},
>          {"name" : "test-dhe-rsa-key-exchange-with-bad-messages.py"},
>          {"name" : "test-tls13-version-negotiation.py"},
> ```

the names should be sorted alphabetically

---

*[tests/tlslite-ng-random-subset.json, line 81 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCdAbGs9Ee_SkPx_tLp:-LCdAbGs9Ee_SkPx_tLq:b-u1h438) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/0e2b6a49e3a7afde7895bcc654d56930e458007b/tests/tlslite-ng-random-subset.json#L81)):*
> ```JSON
>          {"name" : "test-dhe-rsa-key-exchange-signatures.py"},
>          {"name" : "test-dhe-rsa-key-exchange-with-bad-messages.py"},
>          {"name" : "test-tls13-version-negotiation.py"},
> ```

the names should be sorted alphabetically

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/380)*

**Comment by tomato42** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/test-tls13-version-negotiation.py, line 160 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCdZ3JM0eiNkxbIZ7Y-:-LCdZ3JO2u7OUlezT42U:b-tn20vq) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/ed16593a6c070f9f64216ba801e89e0bc846b1a0/scripts/test-tls13-version-negotiation.py#L160)):*
> ```Python
>         node = node.add_child(ExpectAlert())
>         node.next_sibling = ExpectClose()
>         conversations["tls 1.3 negotiation with TLS 1." + str(version_id) + " in record layer"] = conversation
> ```

please use [`format()`](https://docs.python.org/2/library/stdtypes.html#str.format) for string formatting, also that doesn't seem right to me – 0x0300 is SSL 3, 0x0301 is TLS 1.0, while here it will be reported as TLS 1.1, won't it?

---

*[scripts/test-tls13-version-negotiation.py, line 182 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCdZrdO-uf_ZJEq59Fb:-LCdZrdO-uf_ZJEq59Fc:b-uw6xu4) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/ed16593a6c070f9f64216ba801e89e0bc846b1a0/scripts/test-tls13-version-negotiation.py#L182)):*
> ```Python
>         .create(sig_algs)
>     node = node.add_child(ClientHelloGenerator(ciphers, extensions=ext))
>     node = node.add_child(ExpectAlert(AlertLevel.fatal, 70))
> ```

please use `AlertDescription.protocol_version` for readability

---

*[scripts/test-tls13-version-negotiation.py, line 183 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCdZgjC0pDpFa0zsCk0:-LCdZgjC0pDpFa0zsCk1:b3rijep) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/ed16593a6c070f9f64216ba801e89e0bc846b1a0/scripts/test-tls13-version-negotiation.py#L183)):*
> ```Python
>     node = node.add_child(ClientHelloGenerator(ciphers, extensions=ext))
>     node = node.add_child(ExpectAlert(AlertLevel.fatal, 70))
>     conversations["tls 1.10 only"] = conversation
> ```

isn't 0x0309 TLS 1.8?

---

*[scripts/test-tls13-version-negotiation.py, line 198 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCd_m0O2cmvOl2TrVcV:-LCd_m0O2cmvOl2TrVcW:b-tlxehp) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/ed16593a6c070f9f64216ba801e89e0bc846b1a0/scripts/test-tls13-version-negotiation.py#L198)):*
> ```Python
>     ext[ExtensionType.key_share] = ClientKeyShareExtension().create(key_shares)
>     ext[ExtensionType.supported_versions] = SupportedVersionsExtension()\
>         .create([(3,9), (3, 3)])
> ```

nit: missing space after comma

---

*[scripts/test-tls13-version-negotiation.py, line 212 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCd_WSrCVl8AbMLU1La:-LCd_WSrCVl8AbMLU1Lb:b-jti2rm) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/ed16593a6c070f9f64216ba801e89e0bc846b1a0/scripts/test-tls13-version-negotiation.py#L212)):*
> ```Python
>         .create(sig_algs)
>     # verify that there is no supported versions in server hello
>     node = node.add_child(ExpectServerHello(version = (3,3),\
> ```

nit: unnecessary `\` between parentheses, missing space after `,` in tuple, unnecessary spaces around `=`

---

*[scripts/test-tls13-version-negotiation.py, line 228 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCd_EmU-7W7hoHBQ02R:-LCd_EmU-7W7hoHBQ02S:b52h277) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/ed16593a6c070f9f64216ba801e89e0bc846b1a0/scripts/test-tls13-version-negotiation.py#L228)):*
> ```Python
>     node = node.add_child(ExpectAlert())
>     node.next_sibling = ExpectClose()
>     conversations["fallback from TLS 1.10 to 1.2"] = conversation
> ```

same here, I think 0x0309 is TLS 1.8 – 0x0301 is TLS 1.0, 0x0303 is TLS 1.2...

---

*[scripts/test-tls13-version-negotiation.py, line 273 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCd_vPp0_kmdsmR3aV9:-LCd_vPp0_kmdsmR3aVA:b-tlar15) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/ed16593a6c070f9f64216ba801e89e0bc846b1a0/scripts/test-tls13-version-negotiation.py#L273)):*
> ```Python
>     node = node.add_child(ExpectAlert())
>     node.next_sibling = ExpectClose()
>     conversations["fallback from TLS 1.10 to 1.1"] = conversation
> ```

here it looks like a wrong version too

---

*[scripts/test-tls13-version-negotiation.py, line 295 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCdbesIBKdq-UT2FODx:-LCdbesIBKdq-UT2FODy:b-p5oakx) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/ed16593a6c070f9f64216ba801e89e0bc846b1a0/scripts/test-tls13-version-negotiation.py#L295)):*
> ```Python
>     node = node.add_child(ClientHelloGenerator(ciphers, version=(3, 4), extensions=ext))
>     # negotiate TLS 1.2 or fail
>     node = node.add_child(ExpectServerHello(version = (3,3),\
> ```

nit: whitespace, unnecessary `\`

---

*[scripts/test-tls13-version-negotiation.py, line 297 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCda7JjEUZn11Bjd_B9:-LCda7JjEUZn11Bjd_BA:b-5kxizc) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/ed16593a6c070f9f64216ba801e89e0bc846b1a0/scripts/test-tls13-version-negotiation.py#L297)):*
> ```Python
>     node = node.add_child(ExpectServerHello(version = (3,3),\
>                           extensions={ExtensionType.renegotiation_info:None}))
>     node.next_sibling = ExpectAlert()
> ```

why fail is allowed?

---

*[scripts/test-tls13-version-negotiation.py, line 336 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCdaOKv2UWRuHUAD2ID:-LCdaOKv2UWRuHUAD2IE:bhtx8m4) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/ed16593a6c070f9f64216ba801e89e0bc846b1a0/scripts/test-tls13-version-negotiation.py#L336)):*
> ```Python
>     node = node.add_child(ExpectServerHello(version = (3,3),\
>                           extensions={ExtensionType.renegotiation_info:None}))
>     node.next_sibling = ExpectAlert()
> ```

same here, why fail is allowed?

---

*[scripts/test-tls13-version-negotiation.py, line 351 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCdaSGd0ZuIV89IIv4X:-LCdaSGd0ZuIV89IIv4Y:b-e2i7uf) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/ed16593a6c070f9f64216ba801e89e0bc846b1a0/scripts/test-tls13-version-negotiation.py#L351)):*
> ```Python
>     node = node.add_child(ExpectAlert())
>     node.next_sibling = ExpectClose()
>     conversations["TLS 1.10 in client hello legacy field"] = conversation
> ```

again, version

---

*[scripts/test-tls13-version-negotiation.py, line 367 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCdbWR2-aXpJm1JiB4s:-LCdbWR2-aXpJm1JiB4t:bejvyzn) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/ed16593a6c070f9f64216ba801e89e0bc846b1a0/scripts/test-tls13-version-negotiation.py#L367)):*
> ```Python
>     ext[ExtensionType.key_share] = ClientKeyShareExtension().create(key_shares)
>     ext[ExtensionType.supported_versions] = SupportedVersionsExtension()\
>         .create([(3,0)])
> ```

nit: space after comma missing

---

*[scripts/test-tls13-version-negotiation.py, line 375 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCdaXyQ3FW0CU137lws:-LCdaXyQ3FW0CU137lwt:b-xd2ndi) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/ed16593a6c070f9f64216ba801e89e0bc846b1a0/scripts/test-tls13-version-negotiation.py#L375)):*
> ```Python
>         .create(sig_algs)
>     node = node.add_child(ClientHelloGenerator(ciphers, extensions=ext))
>     node = node.add_child(ExpectAlert(AlertLevel.fatal, 70))
> ```

please use `AlertDescription`

---

*[scripts/test-tls13-version-negotiation.py, line 387 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCdamLU5T28bNRh6i0V:-LCdamLU5T28bNRh6i0W:ba3syr7) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/ed16593a6c070f9f64216ba801e89e0bc846b1a0/scripts/test-tls13-version-negotiation.py#L387)):*
> ```Python
>                                                ssl2=True))
>     node = node.add_child(ExpectAlert())
>     conversations["SSL 2.0 ClientHello with TLS 1.3 version and ciphersuites"] = conversation
> ```

"...and only TLS 1.3 ciphersuites"

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/380)*

**Comment by tomato42** [comment]
>> why fail is allowed?

>In these cases the protocol suggested either options.

and we will handle them through detection script in the future, for now it needs to be strict and expect one specific behaviour

if you want to support either, then that behaviour should be consistent across the different option and enabled through a switch to the script

**Comment by tomato42** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/tlslite-ng.json, line 78 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCifVg_2TlRSFamUlVU:-LCifVg_2TlRSFamUlVV:big61tq) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/ed16593a6c070f9f64216ba801e89e0bc846b1a0/tests/tlslite-ng.json#L78)):*
> ```JSON
>                    "arguments" : ["-e", "fallback from TLS 1.10 to 1.1",
>                          "-e", "SSL 3.0 in supported version",
>                          "-e", "tls 1.10 only"
> ```

this should be fixed with https://github.com/tomato42/tlslite-ng/pull/257

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/380)*

**Comment by nmav** [comment]
> this should be fixed with tomato42/tlslite-ng#257

what does this mean for this PR?

**Comment by nmav** [comment]
> if you want to support either, then that behaviour should be consistent across the different options and enabled through a switch to the script

I've added a switch to modify behavior of the script. I've also enabled the scripts tlsfuzzer doesn't work on.

**Comment by tomato42** [comment]
> > this should be fixed with tomato42/tlslite-ng#257

> this is still not merged. what does this mean for this PR?

that when the travis is forced to re-run the tests, it will use the new tlslite-ng but you won't need to rebase the PR to force it to do it

**Comment by tomato42** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[scripts/test-tls13-version-negotiation.py, line 46 at r4](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCmuMBeDkrMC1vmfp8q:-LCmuMBeDkrMC1vmfp8r:boy726r) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/56294d71d7c55d9eaea068cbc6b3e58f9de6d4c2/scripts/test-tls13-version-negotiation.py#L46)):*
> ```Python
>     print(" -n num         only run `num` random tests instead of a full set")
>     print("                (excluding \"sanity\" tests)")
>     print(" -c             modify test behavior for server which closes connection or")
> ```

long options for script-specific settings probably would be better... I want to remove the boilerplate and that will require unification of options, if the special ones are all long options then it would make collisions less likely

---

*[scripts/test-tls13-version-negotiation.py, line 47 at r4](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCmw0wQ-_a0Scah9GcV:-LCmw0wQ-_a0Scah9GcW:b-vl76cu) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/56294d71d7c55d9eaea068cbc6b3e58f9de6d4c2/scripts/test-tls13-version-negotiation.py#L47)):*
> ```Python
>     print("                (excluding \"sanity\" tests)")
>     print(" -c             modify test behavior for server which closes connection or")
>     print("                sends alert on invalid version on ClientHello legacy version field")
> ```

I find it a bit hard to comprehend, how about "expect the server to close the connection on invalid version in ClientHello legacy_version field"?

---

*[scripts/test-tls13-version-negotiation.py, line 54 at r4](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCmusiX4QaqtH_v_zoY:-LCmusiY2RiZBwMRVxAf:bicpm3w) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/56294d71d7c55d9eaea068cbc6b3e58f9de6d4c2/scripts/test-tls13-version-negotiation.py#L54)):*
> ```Python
>     host = "localhost"
>     port = 4433
>     closeconn = 0
> ```

`True` and `False` would be more pythonic here

---

*[scripts/test-tls13-version-negotiation.py, line 137 at r4](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCmwxXN1BZjX_rZZfqH:-LCmwxXN1BZjX_rZZfqI:bnr9whm) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/56294d71d7c55d9eaea068cbc6b3e58f9de6d4c2/scripts/test-tls13-version-negotiation.py#L137)):*
> ```Python
>         ext[ExtensionType.key_share] = ClientKeyShareExtension().create(key_shares)
>         ext[ExtensionType.supported_versions] = SupportedVersionsExtension()\
>         .create([TLS_1_3_DRAFT, (3, 3)])
> ```

nit: inconsistent indentation

---

*[scripts/test-tls13-version-negotiation.py, line 139 at r4](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCmwzRR2ZJy5Vcq-vPd:-LCmwzRR2ZJy5Vcq-vPe:bnr9whm) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/56294d71d7c55d9eaea068cbc6b3e58f9de6d4c2/scripts/test-tls13-version-negotiation.py#L139)):*
> ```Python
>         .create([TLS_1_3_DRAFT, (3, 3)])
>         ext[ExtensionType.supported_groups] = SupportedGroupsExtension()\
>         .create(groups)
> ```

nit: inconsistent indentation

---

*[scripts/test-tls13-version-negotiation.py, line 143 at r4](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCmx0afAGpJH8KtEOBn:-LCmx0afAGpJH8KtEOBo:bnr9whm) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/56294d71d7c55d9eaea068cbc6b3e58f9de6d4c2/scripts/test-tls13-version-negotiation.py#L143)):*
> ```Python
>                 SignatureScheme.rsa_pss_pss_sha256]
>         ext[ExtensionType.signature_algorithms] = SignatureAlgorithmsExtension()\
>         .create(sig_algs)
> ```

nit: inconsistent indentation

---

*[scripts/test-tls13-version-negotiation.py, line 153 at r4](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCmx2JaA3jR5fTz_mDj:-LCmx2JaA3jR5fTz_mDk:bnr9whm) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/56294d71d7c55d9eaea068cbc6b3e58f9de6d4c2/scripts/test-tls13-version-negotiation.py#L153)):*
> ```Python
>         node = node.add_child(FinishedGenerator())
>         node = node.add_child(ApplicationDataGenerator(
>         bytearray(b"GET / HTTP/1.0\r\n\r\n")))
> ```

nit: inconsistent indentation

---

*[scripts/test-tls13-version-negotiation.py, line 262 at r4](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCmx79Q5QHpB_vy6c6m:-LCmx79Q5QHpB_vy6c6n:b-aszbcv) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/56294d71d7c55d9eaea068cbc6b3e58f9de6d4c2/scripts/test-tls13-version-negotiation.py#L262)):*
> ```Python
>         .create(sig_algs)
>     # verify that there is no supported versions in server hello
>     node = node.add_child(ExpectServerHello(version = (3,2),\
> ```

nit: unnecessary `\` in parentheses 

---

*[scripts/test-tls13-version-negotiation.py, line 300 at r4](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCmv1bf9-0Xqj-vCZfb:-LCmv1bf9-0Xqj-vCZfc:b-1fr0pm) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/56294d71d7c55d9eaea068cbc6b3e58f9de6d4c2/scripts/test-tls13-version-negotiation.py#L300)):*
> ```Python
>     node = node.add_child(ClientHelloGenerator(ciphers, version=(3, 4), extensions=ext))
>     # negotiate TLS 1.2 or fail
>     if closeconn == 0:
> ```

`else:` case missing, explicit `ExpectClose` would make it easier to read:
```python
if closeconn:
   node = node.add_child(ExpectClose())
else:
   ...
```

FYI: python automatically casts objects to bool for use in `if` statements, so a `if not closeconn` would have been more pythonic

---

*[scripts/test-tls13-version-negotiation.py, line 339 at r4](https://reviewable.io/reviews/tomato42/tlsfuzzer/380#-LCmxTRvDd-nQh2HZF_Q:-LCmxTRvDd-nQh2HZF_R:b-2guby3) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/56294d71d7c55d9eaea068cbc6b3e58f9de6d4c2/scripts/test-tls13-version-negotiation.py#L339)):*
> ```Python
>     node = node.add_child(ClientHelloGenerator(ciphers, version=(3, 9), extensions=ext))
>     # negotiate TLS 1.2 or fail
>     if closeconn == 0:
> ```

same here

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/380)*

**Comment by nmav** [comment]
Updated

**Comment by tomato42** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/380)*

**Comment by tomato42** [comment]
thank you!

**Pull request merged**
