### PR TITLE
Add test to check tls13 client certificates

### LINKED ISSUE #198: TLS1.3 client certificate support [in-handshake variant]
add support for using client certificates in TLS 1.3, when the server asks for client certificates during the initial handshake.

depends on https://github.com/tomato42/tlslite-ng/issues/207

### PR DESCRIPTION
**Pull request by simo5**
Tests new TLS 1.3 client certificate support in tlslite-ng

### Description
Adds support for sending and receiving Client Certificates in TLS 1.3

### Motivation and Context
Fixes #198 

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL
  - [ ] NSS
  - [ ] GnuTLS
- [ ] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/491)

### CODE REVIEW

**Comment by simo5** [comment]
This PR depends on https://github.com/tomato42/tlslite-ng/pull/333

**Comment by tomato42** [comment]
This pull request **fixes 1 alert** when merging 8039fffc0711c4b1201a43b3fc06b479dff45e3d into b9dec4fde7bedfac90850b86c2c3f644349f6c33 - [view on LGTM.com](https://lgtm.com/projects/g/tomato42/tlsfuzzer/rev/pr-2c4a74a10f37cf5bf1ec5fd214854d48f135771f)

**fixed alerts:**

* 1 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by simo5** [comment]
> please update copyright

ok

> > version = 2
> 
> isn't it `1`?

will fix

> `s:` not handled

will remove

> in `test-certificate-veriy.py` the `sanity` case is checking if the server accepts a certificate, so for consistency I think it would be better to keep that behaviour in TLS 1.3 too
> 
> the "no client certificate" could be a separate test

I am following the footprints of test-certificate-request, where the no
certificate test is the sanity one, and then 'with certificate' is one
of the tests.

IMO it makes more sense this way, as "sanity" should just check that
the server speaks TLS1.3 and sends the request for certificate, then
the "actual" test, checks ceritficate auth works.


> the check for advertised signatures in CertificateRequest is missing

will check

> the names should be sorted alphabetically

ok

**Comment by tomato42** [comment]
This pull request **fixes 1 alert** when merging 7817ac001ff7a8ed32465dbdea147264b0fdd70d into b9dec4fde7bedfac90850b86c2c3f644349f6c33 - [view on LGTM.com](https://lgtm.com/projects/g/tomato42/tlsfuzzer/rev/pr-66c3e4444440f737fc980b158e9e48a48c28bf31)

**fixed alerts:**

* 1 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by tomato42** [comment]
This pull request **fixes 1 alert** when merging d18e9338ede429dbc44a9d9f98ee3fd8d23220ce into cd77aa00f4f20e4399d8ab826e9f17db3231c219 - [view on LGTM.com](https://lgtm.com/projects/g/tomato42/tlsfuzzer/rev/pr-9c9b943edd376b22a0eab162920ce585354bc87d)

**fixed alerts:**

* 1 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by tomato42** [comment]
This pull request **fixes 1 alert** when merging 630f84edf5c4f05ef68e1f3c9fc4b4a75843ed51 into cd77aa00f4f20e4399d8ab826e9f17db3231c219 - [view on LGTM.com](https://lgtm.com/projects/g/tomato42/tlsfuzzer/rev/pr-52362872c65b45f41e3e7f8365d5bc70a136d0d9)

**fixed alerts:**

* 1 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by tomato42** [comment]
This pull request **fixes 1 alert** when merging 8737d64d62b67275ea01d49f94fb0ab3e9fc1d06 into cd77aa00f4f20e4399d8ab826e9f17db3231c219 - [view on LGTM.com](https://lgtm.com/projects/g/tomato42/tlsfuzzer/rev/pr-0c4f6b0c675c92c355ae9717ac160d678de5c29b)

**fixed alerts:**

* 1 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by tomato42** [comment]
perfect, thank you!

**Pull request merged**
