### PR TITLE
ECDSA support on client side

### LINKED ISSUE #197: Add support for ECDSA certificates
Add support for ECDSA certificates, both on client and server side.

Since behaviour of the `signature_algorithms` extension is different for TLS 1.2 and TLS 1.3 – in TLS 1.3 the curve is bound to a hash algorithm – it's possible for the implementation to be lazy and use the same negotiation mechanism for both, possibly causing issues in either of those protocols.

resolves part of #55, depends on https://github.com/tomato42/tlslite-ng/issues/52

### PR DESCRIPTION
**Pull request by tomato42**
### Description

Add support for making signatures in CertificateVerify using ECDSA keys

### Motivation and Context

#543
fixes #197 

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
   - no, see #543
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL
  - [x] NSS
  - [x] GnuTLS [gnutls#848](https://gitlab.com/gnutls/gnutls/issues/848)
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/604)

### CODE REVIEW

**Comment by ueno** [comment]
___
*[tests/test_tlsfuzzer_messages.py, line 1637 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/604#-Ls18_Mj6M79x5nSimA3:-Ls18_Mj6M79x5nSimA4:b7kiqkv) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/5f5a810b21cf8bc61a3d3da031b4363c3249ccbe/tests/test_tlsfuzzer_messages.py#L1637)):*
> ```
> one the one
> ```
typo?

**Comment by ueno** [comment]
___
*[tlsfuzzer/messages.py, line 962 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/604#-Ls1Aj7ZAF1zJ7FwtPp0:-Ls1Aj7ZAF1zJ7FwtPp1:bry2irg) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/5f5a810b21cf8bc61a3d3da031b4363c3249ccbe/tlsfuzzer/messages.py#L962)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         if key_alg in ("rsa", "rsa-pss"):
>             return CertificateVerifyGenerator._sig_alg_for_rsa_key(
>                 key_alg, accept_sig_algs, version)
>         assert key_alg == "ecdsa"
>         return CertificateVerifyGenerator._sig_alg_for_ecdsa_key(
>             accept_sig_algs, version, key)
> ```
</details>

instead of manually writing the conditionals, how about using the same function signature for `_sig_alg_for_*_key` and dispatch with a table? something like:
```python
sig_alg_for_key = {
  "rsa": CertificateVerifyGenerator._sig_alg_for_rsa_key,
  "rsa-pss": CertificateVerifyGenerator._sig_alg_for_rsa_key,
  "ecdsa": CertificateVerifyGenerator._sig_alg_for_ecdsa_key
}

sig_alg_for_key[key_alg](key_alg, accept_sig_algs, version, key)
```

**Comment by ueno** [comment]
___
*[tlsfuzzer/messages.py, line 1037 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/604#-Ls1C3rO8XSyw7RrYxta:-Ls1C3rO8XSyw7RrYxtb:bnqlf8z) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/5f5a810b21cf8bc61a3d3da031b4363c3249ccbe/tlsfuzzer/messages.py#L1037)):*
> ```
> ecda
> ```
typo?

**Comment by ueno** [comment]
___
*[scripts/test-ecdsa-in-certificate-verify.py, line 1 at r4](https://reviewable.io/reviews/tomato42/tlsfuzzer/604#-Ls1Ch4e1KgoaRP3icqz:-Ls1Ch4e1KgoaRP3icr-:byrqb4o) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/2542d694fe111bf7c3d631eee8605074e033c07a/scripts/test-ecdsa-in-certificate-verify.py#L1)):*
> ```
> 2015
> ```
2019?

**Comment by tomato42** [comment]
Thanks for review!

**Pull request merged**
