### PR TITLE
Cache X509 certs

### PR DESCRIPTION
**Pull request by tomato42**
### Description

as parsing certificates is quite expensive, and we can expect
that server will provide us with the same certificate over and over
we can just parse it once and reuse for future connections

as this is based on an instance, we get caching based on
connection and as such, used ClientHello

### Motivation and Context

faster testing, faster test execution

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [ ] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [ ] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [ ] new and modified scripts were ran against popular TLS implementations:
  - [ ] OpenSSL
  - [x] NSS
  - [x] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/703)

### CODE REVIEW

**Comment by ueno** [comment]
___
*[tlsfuzzer/expect.py, line 939 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/703#-MHvfc8vBy4wXCOYAxa_:-MHvfc8vBy4wXCOYAxaa:bsq59rk) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/b4411d4690794783fc42e5fd1665d29e4ff75da0/tlsfuzzer/expect.py#L939)):*
> ```Python
>         self.cert_type = cert_type
>         self._old_cert = None
>         self._old_cert_bytes = None
> ```

Is it sufficient to cache only one cert per instance? Perhaps it might be more useful to cache per class or across all the conversations defined in a script?

**Review by ueno — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/703)* status: all files reviewed, 1 unresolved discussion (waiting on @tomato42)

**Review by tomato42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/703)* status: all files reviewed, 1 unresolved discussion (waiting on @ueno)

___
*[tlsfuzzer/expect.py, line 939 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/703#-MHvfc8vBy4wXCOYAxa_:-MHvjps5B7ucaaIDLbbG:b-vrqfy4) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/b4411d4690794783fc42e5fd1665d29e4ff75da0/tlsfuzzer/expect.py#L939)):*
<details><summary><i>Previously, ueno (Daiki Ueno) wrote…</i></summary><blockquote>

Is it sufficient to cache only one cert per instance? Perhaps it might be more useful to cache per class or across all the conversations defined in a script?
</blockquote></details>

yes, it would be better to cache per class, but then it would make it more complex
at the same time, it mostly affects timing tests, like the bleichenbacher or Lucky13, where we run the same two dozen scripts few million times, so additional speedup from caching per class would be minimal
(and even for those million connections, I see speed up on the order of 20-30%, so for fuzzing tests it wouldn't help much)

**Review by ueno — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/703#-:-MHvlrk23FIc4D2aXkGm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ueno)

**Pull request merged**
