### PR TITLE
fix for issue 221

### LINKED ISSUE #221: update test-rsa-pss-sigs-on-certificate-verify.py for TLS1.3
### System Information

| Type                  | Version/Name |
| --------------------- | ------------ |
| Operating System Name | Ubuntu |
| Operating System Version | trusty 14.04.5  (Travis) |
| Python version        | Python 3.5.5  |
| tlslite-ng version    | 0.8.0-alpha3 |

### Problem description
`test-rsa-pss-sigs-on-certificate-verify.py` fails when run against tlslite-ng

but because in the Travis-CI only a subset of tests in `test-rsa-pss-sigs-on-certificate-verify.py` is run (through the `tlslite-ng-random-subset.json`), the issue is masked.

(Either the runner, or the `tlslite-ng-random-subset.json` script, should be updated so that this case is not skipped randomly)

### Describe how to reproduce the problem
```
python tests/scripts_retention.py tests/tlslite-ng.json `which tls.py`
```

### Include errors or backtraces

```
test-rsa-pss-sigs-on-certificate-verify.py:stdout:check CertificateRequest sigalgs ...
test-rsa-pss-sigs-on-certificate-verify.py:stdout:Error encountered while processing node <tlsfuzzer.expect.ExpectCertificateRequest object at 0x7f330e950668> (child: <tlsfuzzer.expect.ExpectServerHelloDone object at 0x7f330e9506a0>) with last message being: <tlslite.messages.Message object at 0x7f330e377240>
test-rsa-pss-sigs-on-certificate-verify.py:stdout:Error while processing
test-rsa-pss-sigs-on-certificate-verify.py:stdout:Traceback (most recent call last):
test-rsa-pss-sigs-on-certificate-verify.py:stdout:  File "scripts/test-rsa-pss-sigs-on-certificate-verify.py", line 486, in main
test-rsa-pss-sigs-on-certificate-verify.py:stdout:    runner.run()
test-rsa-pss-sigs-on-certificate-verify.py:stdout:  File "/home/travis/build/tomato42/tlsfuzzer/tlsfuzzer/runner.py", line 212, in run
test-rsa-pss-sigs-on-certificate-verify.py:stdout:    node.process(self.state, msg)
test-rsa-pss-sigs-on-certificate-verify.py:stdout:  File "/home/travis/build/tomato42/tlsfuzzer/tlsfuzzer/expect.py", line 697, in process
test-rsa-pss-sigs-on-certificate-verify.py:stdout:    self.sig_algs)
test-rsa-pss-sigs-on-certificate-verify.py:stdout:AssertionError: Unexpected sig algs. Got: [(8, 6), (8, 11), (8, 5), (8, 10), (8, 4), (8, 9), (6, 1), (5, 1), (4, 1), (3, 1), (2, 1)], expected: [(8, 6), (8, 5), (8, 4), (6, 1), (5, 1), (4, 1), (3, 1), (2, 1)]
```

### PR DESCRIPTION
**Pull request by ep69**
### Description
Fixes problems with randomly skipping important sigalg test and different expected sigalgs.

### Motivation and Context
fixes #221

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [ ] OpenSSL
  - [ ] NSS
  - [ ] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/379)

### CODE REVIEW

**Comment by tomato42** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tests/tlslite-ng.json, line 200 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/379#-LCcnIhb4AAwASfK8DeX:-LCcnIhb4AAwASfK8DeY:bcolxij) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/f0a33e7d184e2ce84dc7f0154b3ac4e204c86685/tests/tlslite-ng.json#L200)):*
> ```JSON
>           "arguments" : ["-k", "tests/clientX509Key.pem",
>                          "-c", "tests/clientX509Cert.pem",
>                          "-s", "8+6 8+11 8+5 8+10 8+4 8+9 6+1 5+1 4+1 3+1 2+1"]
> ```

please add a comment stating why this -s is necessary

---

*[tests/tlslite-ng-random-subset.json, line 211 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/379#-LCcnQOS3UgYYgbfHo6P:-LCcnQOS3UgYYgbfHo6Q:bt3k2vo) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/f0a33e7d184e2ce84dc7f0154b3ac4e204c86685/tests/tlslite-ng-random-subset.json#L211)):*
> ```JSON
>                          "-k", "tests/clientX509Key.pem",
>                          "-c", "tests/clientX509Cert.pem",
>                          "-s", "8+6 8+11 8+5 8+10 8+4 8+9 6+1 5+1 4+1 3+1 2+1"]
> ```

same here, why `-s` was added

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/379)*

**Comment by ep69** [comment]
Added the requested comments.

**Comment by tomato42** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/379)*

**Comment by tomato42** [comment]
thanks

**Pull request merged**
