### PR TITLE
test TLS1.3 zero-length alert behavior

### LINKED ISSUE #353: TLS 1.3 zero-length alert records
# New test script idea

## What TLS message this idea relates to?

Alert

## What is the behaviour the test script should test?

send an encrypted record layer (using early data, handshake or application keys) with an empty payload but Alert ContentType, verify that it is rejected with `unexpected_message` alert

## Are there scripts that test related functionality?

not for tls1.3

## Additional information

verify that the padding requirements for records are checked by server

### PR DESCRIPTION
**Pull request by nmav**
### Description

That verifies that non-application data messages cannot have zero length.

Resolves #353

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [ ] all new and existing tests pass (see Travis CI results)
  - tlslite: AssertionError: Expected alert description "unexpected_message" does not match received "decode_error"
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL (succeeds)
  - [ ] NSS
  - [x] GnuTLS (fails with wrong alert)
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/381)

### CODE REVIEW

**Comment by tomato42** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/tomato42/tlsfuzzer/381#-LCiY3C_-4xOwDLdykeM:-LCiY3C_-4xOwDLdykeN:b-amro0m) (no related file):*
blocked on #386 

---

*[scripts/test-tls13-empty-alert.py, line 154 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/381#-LCiYO8MA3f5A3QgThkK:-LCiYO8MA3f5A3QgThkL:b-ehk1oe) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/b2e43954dde780acc54be74cd0b77b600270a4a0/scripts/test-tls13-empty-alert.py#L154)):*
> ```Python
>     node.add_child(cycle)
> 
>     node.next_sibling = ExpectAlert(AlertLevel.fatal, AlertDescription.unexpected_message)
> ```

`ExpectClose` as a child of `ExpectAlert` missing – we need to make sure that the server actually closes the connection

---

*[tests/tlslite-ng.json, line 160 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/381#-LCiYgjqEog9tTnNAwQw:-LCiYgjqEog9tTnNAwQx:b-bp5nfw) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/b2e43954dde780acc54be74cd0b77b600270a4a0/tests/tlslite-ng.json#L160)):*
> ```JSON
>          {"name" : "test-tls13-conversation.py"},
>          {"name" : "test-tls13-empty-alert.py",
>                    "exp_pass" : false},
> ```

I already have fix for this issue (https://github.com/tomato42/tlslite-ng/pull/259), so I'm a bit crass about merging that expect failure...

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/381)*

**Comment by nmav** [comment]
Comments addressed and added padding support.

**Comment by tomato42** [comment]
> btw does code climate have an option to not send emails or add comments?

yes, it does, but it's project-wide

**Comment by tomato42** [comment]
thank you!

**Pull request merged**
