### PR TITLE
signature_algorithms_cert compatibility

### LINKED ISSUE #204: signature_algorithms_cert backwards compatibility
update existing scripts to advertise full range of `signature_algorithms_cert` (as far as RSA is concerned) in all test cases that verify support for `signature_algorithms`.

As server should not send certificates that don't match our advertised sig algs, and we're trying to coerce the server to use specific signature algorithm on the SKE (or CV in TLS1.3) message, we don't want to confuse it with cert selection (where we will accept anything it sends, as long as it's RSA).

add a test to travis CI script that checks for this error in the future (that if a file has reference to `signature_algorithms` it also references `signature_algorithms_cert` (by extending script from https://github.com/tomato42/tlsfuzzer/issues/156)

### PR DESCRIPTION
**Pull request by NoName115**
### Description
Existing test-scripts are updated now, every test that contain signature_algorithms now contain signature_algorithms_cert too.
And also this check is added into  `tests/verify-scripts-json.py` so it's now automated by Travic CI.

### Motivation and Context
fixes #204 

### Checklist
- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [ ] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [ ] new and modified scripts were ran against popular TLS implementations:
  - [ ] OpenSSL
  - [ ] NSS
  - [ ] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/432)

### CODE REVIEW

**Comment by NoName115** [comment]
> looks like test-tls13-hrr.py failed because ext is not using OrderedDict; can you fix it?

Yes, i will fix it.

**Comment by NoName115** [comment]
Fixed.

**Comment by tomato42** [comment]
```
There are 1 scripts that are missing signature_algorithms_cert:
test-tls13-session-resumption.py
```
please update to account for the current master changes :)

**Comment by NoName115** [comment]
Fixed and rebased.

**Comment by NoName115** [comment]
Fixed.

**Comment by tomato42** [comment]
awesome! thanks!

**Pull request merged**
