### PR TITLE
fixup ordered_dict for Python 3.9

### PR DESCRIPTION
**Pull request by t184256**
On current Rawhide / Python 3.9 some of the tests fail because `get_ident` has moved again.

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] the changes are also reflected in documentation and code comments
- [ ] all new and existing tests pass (see Travis CI results)
- [ ] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [ ] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [ ] new and modified scripts were ran against popular TLS implementations:
  - [ ] OpenSSL
  - [ ] NSS
  - [ ] GnuTLS
- [ ] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/678)

### CODE REVIEW

**Comment by tomato42** [comment]
maybe we should add `nightly` python version to travis, like in python-ecdsa: https://github.com/warner/python-ecdsa/blob/master/.travis.yml#L62 ?

**Comment by t184256** [comment]
3.9-dev and nightly versions added, though most are allow_failure due to failures to build dependencies

**Review by tomato42 — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/678)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by tomato42** [comment]
looks good, thank you!

**Pull request merged**
