### PR TITLE
TLS 1.3 zero-length data messages test

### LINKED ISSUE #346: TLS 1.3 zero-length (empty) Application Data
# New test script idea

## What TLS message this idea relates to?

Application Data

## What is the behaviour the test script should test?

* Verify that zero-length Application Data records are not rejected by the server and server will continue processing messages after
* verify that zero-length Application Data records received after processing a handshake record fragment are rejected with `unexpected_message` alert
* verify that zero-length Application Data records during handshake (just before Finished, so that it is encrypted) will cause abort with `unexpected_message` alert

also test with large padding

## Are there scripts that test related functionality?

`scripts/test-zero-length-data.py`

## Additional information

test to verify if the server accepts zero-length fragments

### PR DESCRIPTION
**Pull request by ansasaki**
### Description

This adds a new test script for TLS 1.3 zero-length data messages handling test ``scripts/test-tls13-zero-length-data.py``. 

### Motivation and Context

This fixes #346.

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL
  - [x] NSS
  - [x] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/384)

### CODE REVIEW

**Comment by tomato42** [comment]
Reviewed 1 of 1 files at r1, 1 of 2 files at r2, 1 of 2 files at r3.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[requirements.txt, line 1 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/384#-LChj9YM8H7bSwdkD5zk:-LChj9YM8H7bSwdkD5zl:b-51sgl1) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/b85ecdf69720e658d3250a27724cb9df8006cba8/requirements.txt#L1)):*
> ```
> tlslite-ng=0.8.0-alpha5
> ```

it needs to be `==`

---

*[scripts/test-tls13-zero-length-data.py, line 1 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/384#-LChjDzK6GfKRzGpF9qm:-LChjDzK6GfKRzGpF9qn:bh6hlkf) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/b85ecdf69720e658d3250a27724cb9df8006cba8/scripts/test-tls13-zero-length-data.py#L1)):*
> ```Python
> # Author: Hubert Kario, (c) 2018
> ```

wrong copyright

---

*[scripts/test-tls13-zero-length-data.py, line 132 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/384#-LChjUGlD6QRxSmRN1vd:-LChjUGlD6QRxSmRN1ve:b-xk8iue) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/b85ecdf69720e658d3250a27724cb9df8006cba8/scripts/test-tls13-zero-length-data.py#L132)):*
> ```Python
>     ext[ExtensionType.key_share] = ClientKeyShareExtension().create(key_shares)
>     ext[ExtensionType.supported_versions] = SupportedVersionsExtension()\
>         .create([(3, 3), TLS_1_3_DRAFT])
> ```

wrong order of versions

---

*[scripts/test-tls13-zero-length-data.py, line 183 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/384#-LChj_glEGzBPz-1mDe4:-LChj_glEGzBPz-1mDe5:b-xk8iue) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/b85ecdf69720e658d3250a27724cb9df8006cba8/scripts/test-tls13-zero-length-data.py#L183)):*
> ```Python
>     ext[ExtensionType.key_share] = ClientKeyShareExtension().create(key_shares)
>     ext[ExtensionType.supported_versions] = SupportedVersionsExtension()\
>         .create([(3, 3), TLS_1_3_DRAFT])
> ```

wrong order of versions

---

*[scripts/test-tls13-zero-length-data.py, line 236 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/384#-LChjtN87rBg2lDKgdqR:-LChjtN87rBg2lDKgdqS:bx9aecy) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/b85ecdf69720e658d3250a27724cb9df8006cba8/scripts/test-tls13-zero-length-data.py#L236)):*
> ```Python
> 
>     print("TLS 1.3 zero-length Application Data")
>     print("Check if zero-length Application Data records handling\n")
> ```

it feels like "is correct" is missing here

---

*[tests/tlslite-ng.json, line 162 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/384#-LChk-cz8i7Q6YSCi2tc:-LChk-d0-r0PDRLBkNj5:b-j9xol4) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/b85ecdf69720e658d3250a27724cb9df8006cba8/tests/tlslite-ng.json#L162)):*
> ```JSON
>          {"name" : "test-tls13-zero-length-data.py",
>           "comment" : "tlslite-ng do not send alert when zero-length application data while in handshake",
>           "exp_pass" : false},
> ```

do all tests in the script fail? or just one?

---

*[tests/tlslite-ng-random-subset.json, line 172 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/384#-LChk7r8DZkJ_Pbtg4Hr:-LChk7r8DZkJ_Pbtg4Hs:b-2guby3) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/b85ecdf69720e658d3250a27724cb9df8006cba8/tests/tlslite-ng-random-subset.json#L172)):*
> ```JSON
>          {"name" : "test-tls13-zero-length-data.py",
>           "comment" : "tlslite-ng do not send alert when zero-length application data while in handshake",
>           "exp_pass" : false},
> ```

same here

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/384)*

**Comment by tomato42** [comment]
Reviewed 1 of 2 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/384)*

**Comment by ansasaki** [comment]
Review status: 1 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[tests/tlslite-ng.json, line 162 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/384#-LChk-cz8i7Q6YSCi2tc:-LCj0pYv8KsdzQraIzhf:b493i1k) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/b85ecdf69720e658d3250a27724cb9df8006cba8/tests/tlslite-ng.json#L162)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

do all tests in the script fail? or just one?
</blockquote></details>

It does not fail any more after applying https://github.com/tomato42/tlslite-ng/pull/260 

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/384)*

**Comment by ansasaki** [comment]
Tested against https://github.com/tomato42/tlslite-ng/pull/260 and it worked as expected.
The travis tests are failing because I removed the fail expectations. Should work after https://github.com/tomato42/tlslite-ng/pull/260 is merged.

One curious thing is that OpenSSL send the alert correctly in the interleaved case during handshake, but does not send the alert when the zero length app data is sent just before the finished message.

I'll work on the zero length app data with padding before removing the WIP status.

**Comment by tomato42** [comment]
ok, asked nmav to review the other two issues, once he does I'll do a new alpha release

please note the openssl issue, will pick it up later

**Comment by tomato42** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/384)*

**Comment by tomato42** [comment]
Changes ok, but both NSS and OpenSSL require #388 to be fixed before the test will be runnable against them.

**Comment by tomato42** [comment]
Thank you!

**Pull request merged**
