### PR TITLE
New test-script for tls1.3 with shuffled extensions

### LINKED ISSUE #398: TLS 1.3 HRR handshake, ClientHello shuffled extensions
# New test script idea

## What TLS message this idea relates to?

ClientHello, HelloRetryRequest

## What TLS extension this idea relates to?

generally all ones

## What is the behaviour the test script should test?

check if the second client hello is rejected if the extensions are in different order than they were in the first ClientHello

also test with extension IDs that are still unassigned

## Are there scripts that test related functionality?

none

## Additional information

Test to verify if the server checks if the second ClientHello has minimal modifications to meet the requirements set in HelloRetryRequest

### PR DESCRIPTION
**Pull request by NoName115**
### Description
New test-script for tls1.3 with HRR message in communication.
Script verify that the communication is rejected after second ClientHello, when first & second ClientHello message contain different order of same extensions.

### Motivation and Context
fixes #398 

### Checklist
- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL
  - [x] NSS
  - [x] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/469)

### CODE REVIEW

**Comment by NoName115** [comment]
**tlslite-ng** works fine.
**GnuTLS, Openssl, NSS** sends ServerHello message after second ClientHello.

**Comment by NoName115** [comment]
Fixed.

**tlslite-ng** works fine.
**OpenSSL** Test `'HRR reversed order of unassigned extensions, ext_ids in range from 61492 to 65278'` failed with
```
Error encountered while processing node <tlsfuzzer.expect.ExpectHelloRetryRequest object at 0x7f8f5b284fd0> (child: <tlsfuzzer.expect.ExpectChangeCipherSpec object at 0x7f8f5af04048>) with last message being: <tlslite.messages.Message object at 0x7f8f58dc9ba8>

AssertionError: Unexpected message from peer: Alert(fatal, illegal_parameter)
```
**NSS**
All tests failed with `AssertionError: Expected alert description "illegal_parameter" does not match received "missing_extension"`

**GnuTLS**
All tests failed with `AssertionError: Expected alert description "illegal_parameter" does not match received "handshake_failure"`

**Comment by NoName115** [comment]
Done.

**Comment by tomato42** [comment]
Thank you!

**Pull request merged**
