### PR TITLE
[WIP] Add ability to collect timing information

### LINKED ISSUE #47: Collecting network traffic
Allow tlsfuzzer to collect network traffic (using `tcpdump` or similar) to aid in later debugging and to perform timing analysis.

### PR DESCRIPTION
**Pull request by kosciCZ**
### Description

This PR would add the ability to collect timing information via tcpdump. Although it is now functional it is definitely not ready to merge. I haven't added any test coverage, as everything might be subject to change, and I'll add them once we agree on the general idea on how to solve this. 

So the idea is that the timing can be done on any test, that takes an network interface argument. This is needed, because acquiring the actual interface from socket is difficult and not reliable. Another option was to use `any` as a special value for tcpdump, but that changes the link protocol to [SLL](https://wiki.wireshark.org/SLL) and that didn't work reliably with the packet parsing library. 

Existing tests can be altered minimally to be extended to collect timing information (see `test-bleichenbacher-timing.py`). A log of conversation classes is created during the normal run of the script (excludes sanity tests). If all tests pass, TimingRunner is initialized and executed. This class checks for tcpdump presence, starts packet capturing with filtering only tcp packets to/from the server and then executes all non-sanity conversations as they ran in the normal test. After that, Analysis is run to associate the latency of last server response to a conversation class from the log and result is dumped to a csv file. 

There are more things that should be here/will change, but I wanted to get this out as fast as possible so we can discuss details. Here's a non-exhaustive list:
  - cache warmup (perhaps n-times sanity test?)
  - file structure inside tlsfuzzer
  - ~~arguments names (there's a collision on `-r`)~~
  - allowing to setup cpu affinity for the tcpdump
  - ~~documentation with examples~~
  - ~~deal with dpkt as an optional dependency~~
  - example test is ~~just copied and~~ extended
  - research if this can run on Windows somehow
 
### Motivation and Context

Should fix #47 once completed.
### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] the changes are also reflected in documentation and code comments
- [ ] all new and existing tests pass (see Travis CI results)
- [ ] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [ ] new and modified scripts were ran against popular TLS implementations:
  - [ ] OpenSSL
  - [ ] NSS
  - [ ] GnuTLS
- [ ] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/659)

### CODE REVIEW

**Comment by tomato42** [comment]
overall, looks good, maybe squash some changes together, like the different versions of the lucky13 script?

**Comment by tomato42** [comment]
side note: I'm guessing the timing tests are passing in CI because we don't have tcpdump installed there?
(since they would fail against tlslite-ng I don't want to run them, just trying to understand the passes in CI)

**Comment by kosciCZ** [comment]
> side note: I'm guessing the timing tests are passing in CI because we don't have tcpdump installed there?
> (since they would fail against tlslite-ng I don't want to run them, just trying to understand the passes in CI)

I don't think tcpdump is actually run in tests anywhere, I think I mocked it everywhere. The test are passing and they are being actually run, hence the high coverage.

**Comment by tomato42** [comment]
> > side note: I'm guessing the timing tests are passing in CI because we don't have tcpdump installed there?
> > (since they would fail against tlslite-ng I don't want to run them, just trying to understand the passes in CI)
> 
> I don't think tcpdump is actually run in tests anywhere, I think I mocked it everywhere. The test are passing and they are being actually run, hence the high coverage.

sorry, I misspoke, by "tests" I wanted to say "scripts"—the random-subset json is actually executed in CI

**Comment by tomato42** [comment]
I'm going to merge this PR, please add things that still need to be completed to the issue #106

**Comment by kosciCZ** [comment]
Ah, yes. In the .json files, I did not include the timing arguments, because that would only trip up the CI at this point I think, so as of now, the test cases are ran the usual way.

**Comment by tomato42** [comment]
> Ah, yes. In the .json files, I did not include the timing arguments, because that would only trip up the CI at this point I think, so as of now, the test cases are ran the usual way.

ah, ok

**Comment by tomato42** [comment]
Note: while this PR does provide scripts for #336 and #335, it is missing a runner that is able to handle false positive results that those scripts generate, so it's not usable just yet in CI

**Pull request merged**
