### PR TITLE
new test-script for Finished msg in plaintext

### LINKED ISSUE #390: TLS 1.3 Finished sent in plaintext
# New test script idea

## What TLS message this idea relates to?

Finished, record layer

## What is the behaviour the test script should test?

It is technically possible to send Finished using application data keys (future keys from connection point of view, see #389) or no keys. Extend tlsfuzzer and create a test case which will send Finished using no keys - as plaintext message. Check if it is rejected as unexpected_message (as the `opaque_type` will be wrong)

## Are there scripts that test related functionality?

none

## Additional information

see also #389

### PR DESCRIPTION
**Pull request by NoName115**
### Description
New test-script, which verify that unencrypted Finished msg is rejected with `unexpected_message` by a TLS 1.3 server. Also new class `ResetConnectionState` in tlsfuzzer/messages.py is added, for reseting _writeState, so the messages will be unencrypted.

### Motivation and Context
fixes #390 

### Checklist
- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL
  - [x] NSS
  - [x] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/472)

### CODE REVIEW

**Comment by NoName115** [comment]
Tested with WireShark that Finished msg is a plaintext.

tlslite-ng, OpenSSL works fine.
NSS ended with `AssertionError: Expected alert description "unexpected_message" does not match received "bad_record_mac"`

And GnuTLS failed with
```
Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x7ff4e50d1a58> (child: None) with last message being: <tlslite.messages.Message object at 0x7ff4e50d1f98>
...
AssertionError: Unexpected message from peer: Handshake(new_session_ticket)
```
<details><summary>GnuTLS output</summary>

```
* Accepted connection from IPv4 127.0.0.1 port 51310 on Mon Nov 19 13:53:17 2018
|<5>| REC[0x19a7570]: Allocating epoch #1
|<3>| ASSERT: buffers.c[get_last_packet]:1171
|<5>| REC[0x19a7570]: SSL 3.0 Handshake packet received. Epoch 0, length: 213
|<5>| REC[0x19a7570]: Expected Packet Handshake(22)
|<5>| REC[0x19a7570]: Received Packet Handshake(22) with length: 213
|<5>| REC[0x19a7570]: Decrypted Packet[0] Handshake(22) with length: 213
|<4>| HSK[0x19a7570]: CLIENT HELLO (1) was received. Length 209[209], frag offset 0, frag length: 209, sequence: 0
|<4>| HSK[0x19a7570]: Client's version: 3.3
|<4>| EXT[0x19a7570]: Parsing extension 'Supported Versions/43' (5 bytes)
|<4>| EXT[0x19a7570]: Found version: 3.4
|<4>| EXT[0x19a7570]: Negotiated version: 3.4
|<4>| EXT[0x19a7570]: Parsing extension 'Supported Groups/10' (4 bytes)
|<4>| EXT[0x19a7570]: Received group SECP256R1 (0x17)
|<4>| EXT[0x19a7570]: Selected group SECP256R1
|<4>| EXT[0x19a7570]: Parsing extension 'Signature Algorithms/13' (6 bytes)
|<4>| EXT[0x19a7570]: rcvd signature algo (8.4) RSA-PSS-RSAE-SHA256
|<4>| EXT[0x19a7570]: rcvd signature algo (8.9) RSA-PSS-SHA256
|<4>| HSK[0x19a7570]: Received safe renegotiation CS
|<2>| checking 13.01 (GNUTLS_AES_128_GCM_SHA256) for compatibility
|<3>| ASSERT: server_name.c[gnutls_server_name_get]:235
|<4>| HSK[0x19a7570]: Requested server name: ''
|<4>| HSK[0x19a7570]: checking compat of GNUTLS_AES_128_GCM_SHA256 with certificate[3] (RSA-PSS/X.509)
|<4>| checking cert compat with RSA-PSS-RSAE-SHA256
|<4>| checking cert compat with RSA-PSS-SHA256
|<4>| Selected signature algorithm: RSA-PSS-SHA256
|<2>| Selected (RSA-PSS) cert based on ciphersuite 13.1: GNUTLS_AES_128_GCM_SHA256
|<4>| HSK[0x19a7570]: Selected cipher suite: GNUTLS_AES_128_GCM_SHA256
|<4>| HSK[0x19a7570]: Selected version TLS1.3
|<4>| EXT[0x19a7570]: Parsing extension 'Key Share/51' (71 bytes)
|<4>| EXT[0x19a7570]: Received key share for SECP256R1
|<4>| HSK[0x19a7570]: Selected group SECP256R1 (2)
|<2>| EXT[0x19a7570]: server generated SECP256R1 shared key
|<4>| HSK[0x19a7570]: Safe renegotiation succeeded
|<4>| HSK[0x19a7570]: SessionID: 6c137784bdacb0fe204a4e6dc631dba9709a2c78716e232193f3313a0676675f
|<4>| EXT[0x19a7570]: Not sending extension (Maximum Record Size/1) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (OCSP Status Request/5) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (Client Certificate Type/19) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (Server Certificate Type/20) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (Supported Groups/10) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (Supported EC Point Formats/11) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (SRP/12) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (Signature Algorithms/13) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (SRTP/14) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (Heartbeat/15) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (ALPN/16) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (Encrypt-then-MAC/22) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (Extended Master Secret/23) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (Session Ticket/35) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Preparing extension (Key Share/51) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: sending key share for SECP256R1
|<4>| EXT[0x19a7570]: Sending extension Key Share/51 (69 bytes)
|<4>| EXT[0x19a7570]: Preparing extension (Supported Versions/43) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Sending extension Supported Versions/43 (2 bytes)
|<4>| EXT[0x19a7570]: Not sending extension (Post Handshake Auth/49) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (Safe Renegotiation/65281) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (Server Name Indication/0) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (Cookie/44) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (Early Data/42) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Preparing extension (PSK Key Exchange Modes/45) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (Record Size Limit/28) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Not sending extension (ClientHello Padding/21) for 'TLS 1.3 server hello'
|<4>| EXT[0x19a7570]: Preparing extension (Pre Shared Key/41) for 'TLS 1.3 server hello'
|<4>| HSK[0x19a7570]: SERVER HELLO was queued [155 bytes]
|<5>| REC[0x19a7570]: Preparing Packet Handshake(22) with length: 155 and min pad: 0
|<5>| REC[0x19a7570]: Sent Packet[1] Handshake(22) in epoch 0 and length: 160
|<5>| REC[0x19a7570]: Preparing Packet ChangeCipherSpec(20) with length: 1 and min pad: 0
|<5>| REC[0x19a7570]: Sent Packet[2] ChangeCipherSpec(20) in epoch 0 and length: 6
|<4>| REC[0x19a7570]: Sent ChangeCipherSpec
|<5>| REC[0x19a7570]: Initializing epoch #1
|<5>| REC[0x19a7570]: Epoch #1 ready
|<4>| HSK[0x19a7570]: TLS 1.3 re-key with cipher suite: GNUTLS_AES_128_GCM_SHA256
|<4>| EXT[0x19a7570]: Preparing extension (Maximum Record Size/1) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (OCSP Status Request/5) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Preparing extension (Client Certificate Type/19) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Preparing extension (Server Certificate Type/20) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Preparing extension (Supported Groups/10) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (Supported EC Point Formats/11) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (SRP/12) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (Signature Algorithms/13) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Preparing extension (SRTP/14) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Preparing extension (Heartbeat/15) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Preparing extension (ALPN/16) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (Encrypt-then-MAC/22) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (Extended Master Secret/23) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (Session Ticket/35) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (Key Share/51) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (Supported Versions/43) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (Post Handshake Auth/49) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (Safe Renegotiation/65281) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Preparing extension (Server Name Indication/0) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (Cookie/44) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (Early Data/42) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (PSK Key Exchange Modes/45) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Preparing extension (Record Size Limit/28) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (ClientHello Padding/21) for 'encrypted extensions'
|<4>| EXT[0x19a7570]: Not sending extension (Pre Shared Key/41) for 'encrypted extensions'
|<4>| HSK[0x19a7570]: ENCRYPTED EXTENSIONS was queued [6 bytes]
|<4>| HSK[0x19a7570]: CERTIFICATE was queued [874 bytes]
|<4>| checking cert compat with RSA-PSS-RSAE-SHA256
|<4>| checking cert compat with RSA-PSS-SHA256
|<4>| HSK[0x19a7570]: signing TLS 1.3 handshake data: using RSA-PSS-SHA256 and PRF: SHA256
|<3>| ASSERT: mpi.c[wrap_nettle_mpi_print]:60
|<4>| HSK[0x19a7570]: CERTIFICATE VERIFY was queued [264 bytes]
|<4>| HSK[0x19a7570]: sending finished
|<4>| HSK[0x19a7570]: FINISHED was queued [36 bytes]
|<5>| REC[0x19a7570]: Preparing Packet Handshake(22) with length: 6 and min pad: 0
|<5>| REC[0x19a7570]: Sent Packet[1] Handshake(22) in epoch 1 and length: 28
|<5>| REC[0x19a7570]: Preparing Packet Handshake(22) with length: 874 and min pad: 0
|<5>| REC[0x19a7570]: Sent Packet[2] Handshake(22) in epoch 1 and length: 896
|<5>| REC[0x19a7570]: Preparing Packet Handshake(22) with length: 264 and min pad: 0
|<5>| REC[0x19a7570]: Sent Packet[3] Handshake(22) in epoch 1 and length: 286
|<5>| REC[0x19a7570]: Preparing Packet Handshake(22) with length: 36 and min pad: 0
|<5>| REC[0x19a7570]: Sent Packet[4] Handshake(22) in epoch 1 and length: 58
|<3>| ASSERT: constate.c[_gnutls_epoch_get]:836
|<5>| REC[0x19a7570]: Allocating epoch #2
|<4>| HSK[0x19a7570]: unauthenticated session eligible for early start
|<5>| REC[0x19a7570]: Initializing epoch #2
|<5>| REC[0x19a7570]: Epoch #2 ready
|<4>| HSK[0x19a7570]: TLS 1.3 set write key with cipher suite: GNUTLS_AES_128_GCM_SHA256
|<4>| HSK[0x19a7570]: switching early to application traffic keys
|<4>| HSK[0x19a7570]: NEW SESSION TICKET was queued [203 bytes]
|<5>| REC[0x19a7570]: Preparing Packet Handshake(22) with length: 203 and min pad: 0
|<5>| REC[0x19a7570]: Sent Packet[1] Handshake(22) in epoch 2 and length: 225
|<3>| ASSERT: buffers.c[get_last_packet]:1171
|<5>| REC[0x19a7570]: SSL 3.3 Handshake packet received. Epoch 1, length: 36
|<5>| REC[0x19a7570]: Expected Packet Handshake(22)
|<5>| REC[0x19a7570]: Received Packet Handshake(22) with length: 36
|<3>| ASSERT: aes-gcm-x86-pclmul-avx.c[aesni_gcm_aead_decrypt]:351
|<3>| ASSERT: crypto-api.c[gnutls_aead_cipher_decrypt]:714
|<3>| ASSERT: cipher.c[decrypt_packet_tls13]:873
|<3>| ASSERT: cipher.c[_gnutls_decrypt]:160
|<3>| ASSERT: record.c[_gnutls_recv_in_buffers]:1411
|<0x19a7570>| Discarded message[0] due to invalid decryption
|<3>| ASSERT: buffers.c[_gnutls_handshake_io_recv_int]:1448
|<3>| ASSERT: handshake.c[_gnutls_recv_handshake]:1497
|<3>| ASSERT: tls13/finished.c[_gnutls13_recv_finished]:101
|<3>| ASSERT: handshake-tls13.c[_gnutls13_handshake_server]:481
Error in handshake: Decryption has failed.
|<5>| REC: Sending Alert[2|20] - Bad record MAC
|<5>| REC[0x19a7570]: Preparing Packet Alert(21) with length: 2 and min pad: 0
|<5>| REC[0x19a7570]: Sent Packet[2] Alert(21) in epoch 2 and length: 24
|<5>| REC[0x19a7570]: Start of epoch cleanup
|<5>| REC[0x19a7570]: Epoch #0 freed
|<5>| REC[0x19a7570]: End of epoch cleanup
|<5>| REC[0x19a7570]: Epoch #1 freed
|<5>| REC[0x19a7570]: Epoch #2 freed
```
</details>

**Comment by tomato42** [comment]
This pull request **introduces 1 alert** when merging d388d52d6387962421372969118315fa781d1dbe into d19faaf1c8352fd28b9a951f458063c90d878f0b - [view on LGTM.com](https://lgtm.com/projects/g/tomato42/tlsfuzzer/rev/pr-98d2b6aa1fb7ed083ab312338bb79d705d19c254)

**new alerts:**

* 1 for Missing call to \_\_init\_\_ during object initialization

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by NoName115** [comment]
Fixed.
But firstly we need to merge https://github.com/tomato42/tlsfuzzer/pull/477 for correct testing.

**Comment by NoName115** [comment]
Rebased.

**Comment by tomato42** [comment]
Thank you!

So, how do the implementations behave after those changes?

**Comment by NoName115** [comment]
Thanks for reviews!
**OpenSSL** works fine.
**GnuTLS & NSS** failed with `AssertionError: Expected alert description "unexpected_message" does not match received "bad_record_mac"`

**Comment by tomato42** [comment]
so they try to decrypt without verifying that the external type is correct - please file bugs for that

**Comment by NoName115** [comment]
Reported:
https://bugzilla.mozilla.org/show_bug.cgi?id=1512605
https://gitlab.com/gnutls/gnutls/issues/643

**Pull request merged**
