### PR TITLE
add test-script for unrecognized groups

### LINKED ISSUE #369: TLS 1.3 key_share unrecognised groups
# New test script idea

## What TLS message this idea relates to?

ClientHello

## What TLS extension this idea relates to?

`key_share`

## What is the behaviour the test script should test?

Send a ClientHello with `supported_groups` indicating support for curves not [defined by IANA](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8), provide `key_share` with shares for those groups, verify that server accepts such ClientHello either with a HelloRetryRequest or ServerHello.

Check with
 * just unknown groups in `key_share`, known groups in `supported_groups` (server replies with HRR)
 * just unknown groups in `supported_groups` and `key_share` (server replies with `handshake_failure`)
 * both known and unknown, but unknown listed first (server continues to ServerHello, uses known groups)
 * both with IDs from FFDHE and ECDH range 

## Are there scripts that test related functionality?

none

## Additional information

Check to verity that server does not try to use curves it does not understand

### PR DESCRIPTION
**Pull request by NoName115**
### Description
New test script for testing TLS 1.3 communication with known and unkown groups for supported_groups and key_shares extentions.

### Motivation and Context
fixes #369 

### Checklist
- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL
  - [x] NSS
  - [x] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/440)

### CODE REVIEW

**Comment by NoName115** [comment]
Fixed.

**Comment by NoName115** [comment]
Fixed.

But do you think we should add all 4 combinations of (un)known EC/FFDHE groups for "both known and unknown, but unknown listed first" too?

**Comment by tomato42** [comment]
> But do you think we should add all 4 combinations of (un)known EC/FFDHE groups for "both known and unknown, but unknown listed first" too?

the same logic applies there, so probably yes

**Comment by NoName115** [comment]
Done.

**Comment by NoName115** [comment]
Fixed.

**Comment by NoName115** [comment]
I tested it against openssl (1.1.0-stable) and gnutls(master).
```
openssl (run without --cookie argument)

successful: 20
failed: 12
  'known group ffdhe2048 and unknown groups from EC range, key_share of size 64'
  'known group ffdhe2048 and unknown groups from EC range, key_share of size 128'
  'known group ffdhe2048 and unknown groups from EC range, key_share of size 256'
  'known group ffdhe2048 and unknown groups from FFDHE range, key_share of size 64'
  'known group ffdhe2048 and unknown groups from FFDHE range, key_share of size 128'
  'known group ffdhe2048 and unknown groups from FFDHE range, key_share of size 256'
  'only unknown key_share from EC range, key_share of size 64 + ffdhe2048 in supported_groups'
  'only unknown key_share from EC range, key_share of size 128 + ffdhe2048 in supported_groups'
  'only unknown key_share from EC range, key_share of size 256 + ffdhe2048 in supported_groups'
  'only unknown key_share from FFDHE range, key_share of size 64 + ffdhe2048 in supported_groups'
  'only unknown key_share from FFDHE range, key_share of size 128 + ffdhe2048 in supported_groups'
  'only unknown key_share from FFDHE range, key_share of size 256 + ffdhe2048 in supported_groups'

openssl (run with --cookie arg)

successful: 14
failed: 18
  same as above, but plus:
  'only unknown key_share from EC range, key_share of size 64 + secp256r1 in supported_groups'
  'only unknown key_share from EC range, key_share of size 128 + secp256r1 in supported_groups'
  'only unknown key_share from EC range, key_share of size 256 + secp256r1 in supported_groups'
  'only unknown key_share from FFDHE range, key_share of size 64 + secp256r1 in supported_groups'
  'only unknown key_share from FFDHE range, key_share of size 128 + secp256r1 in supported_groups'
  'only unknown key_share from FFDHE range, key_share of size 256 + secp256r1 in supported_groups'
```

```
gnutls (without --cookie)
successful: 26
failed: 6
  'only unknown supported_groups from EC range, key_share of size 64'
  'only unknown supported_groups from EC range, key_share of size 128'
  'only unknown supported_groups from EC range, key_share of size 256'
  'only unknown supported_groups from FFDHE range, key_share of size 64'
  'only unknown supported_groups from FFDHE range, key_share of size 128'
  'only unknown supported_groups from FFDHE range, key_share of size 256'

gnutls (with --cookie)
successful: 14
failed: 18
  'only unknown key_share from EC range, key_share of size 64 + ffdhe2048 in supported_groups'
  'only unknown key_share from EC range, key_share of size 64 + secp256r1 in supported_groups'
  'only unknown key_share from EC range, key_share of size 128 + ffdhe2048 in supported_groups'
  'only unknown key_share from EC range, key_share of size 128 + secp256r1 in supported_groups'
  'only unknown key_share from EC range, key_share of size 256 + ffdhe2048 in supported_groups'
  'only unknown key_share from EC range, key_share of size 256 + secp256r1 in supported_groups'
  'only unknown key_share from FFDHE range, key_share of size 64 + ffdhe2048 in supported_groups'
  'only unknown key_share from FFDHE range, key_share of size 64 + secp256r1 in supported_groups'
  'only unknown key_share from FFDHE range, key_share of size 128 + ffdhe2048 in supported_groups'
  'only unknown key_share from FFDHE range, key_share of size 128 + secp256r1 in supported_groups'
  'only unknown key_share from FFDHE range, key_share of size 256 + ffdhe2048 in supported_groups'
  'only unknown key_share from FFDHE range, key_share of size 256 + secp256r1 in supported_groups'
  'only unknown supported_groups from EC range, key_share of size 64'
  'only unknown supported_groups from EC range, key_share of size 128'
  'only unknown supported_groups from EC range, key_share of size 256'
  'only unknown supported_groups from FFDHE range, key_share of size 64'
  'only unknown supported_groups from FFDHE range, key_share of size 128'
  'only unknown supported_groups from FFDHE range, key_share of size 256'
```

**Comment by tomato42** [comment]
looks good, thanks!

**Pull request merged**
