### PR TITLE
add a test that offers curves obsoleted in TLS 1.3

### PR DESCRIPTION
**Pull request by t184256**
### Description

The test offers curves obsoleted in TLS 1.3, like secp256k1 or brainpool. They should be handshake_failed.

### Motivation and Context

openssl allows one to negotiate TLS <1.3 curves in TLS 1.3 (https://github.com/openssl/openssl/issues/8369). This is a reproducer for that.

### Checklist

- [ ] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [ ] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [X] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [X] new and modified scripts were ran against popular TLS implementations:
  - [X] OpenSSL
  - [X] NSS
  - [X] GnuTLS
- [ ] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/569)

### CODE REVIEW

**Comment by t184256** [comment]
___
*[scripts/test-tls13-obsolete-curves.py, line 1 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/569#-LnEA4ZgBUFm0s0z4zEj:-LnH95Ak8vl5bhuyAwgo:b-896fix) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/0ed2c6c2054bfaf13a6c095770049f348e7f9612/scripts/test-tls13-obsolete-curves.py#L1)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

please update copyright
</blockquote></details>

Done.

**Comment by t184256** [comment]
___
*[scripts/test-tls13-obsolete-curves.py, line 122 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/569#-LnEAF6q16cOAdzS6rEW:-LnH9RRuA6XPLnWpIGun:b-896fix) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/0ed2c6c2054bfaf13a6c095770049f348e7f9612/scripts/test-tls13-obsolete-curves.py#L122)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

references to IETF pages or RFC numbers are more stable
</blockquote></details>

Done.

**Comment by t184256** [comment]
___
*[scripts/test-tls13-obsolete-curves.py, line 125 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/569#-LnEAlAz3F5zLfW_eG-3:-LnH9Sxu2umkWetIGuGA:b-896fix) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/0ed2c6c2054bfaf13a6c095770049f348e7f9612/scripts/test-tls13-obsolete-curves.py#L125)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

wouldn't `chain(range(), range(), range())` be cleaner?
</blockquote></details>

Done.

**Comment by t184256** [comment]
___
*[scripts/test-tls13-obsolete-curves.py, line 129 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/569#-LnEAyGxAIbLaWsPBtQt:-LnH9Uxx3oFYIZSYZQ6q:b-896fix) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/0ed2c6c2054bfaf13a6c095770049f348e7f9612/scripts/test-tls13-obsolete-curves.py#L129)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

wouldn't `"unknown {0}"` or `"unknown ({0})"` result in nicer formatting?
</blockquote></details>

Done.

**Comment by t184256** [comment]
___
*[scripts/test-tls13-obsolete-curves.py, line 158 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/569#-LnEBOquBd2Scmtwp5N6:-LnH9_wh9t_PTkwajc2W:b-896fix) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/0ed2c6c2054bfaf13a6c095770049f348e7f9612/scripts/test-tls13-obsolete-curves.py#L158)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

we want the server to send the alert *and* close the connection, so we should use `add_child` not `next_sibling`
</blockquote></details>

Done.

**Comment by t184256** [comment]
___
*[scripts/test-tls13-obsolete-curves.py, line 199 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/569#-LnEBmt21a-kuMHHmdeO:-LnH9cbi-6HpR6wvUe5Y:b-896fix) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/0ed2c6c2054bfaf13a6c095770049f348e7f9612/scripts/test-tls13-obsolete-curves.py#L199)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

how about "Check that TLS 1.3 server will not use obsoleted curves and will reject the connection with handshake_failure alert"?
</blockquote></details>

Done.

**Comment by tomato42** [comment]
looks good, thanks!

**Comment by tomato42** [comment]
actually, I think the expected alert is incorrect, see #539

**Pull request merged**
