### PR TITLE
Added the script for issue #156

### LINKED ISSUE #156: Verify that new scripts are added to json files
When a new test script is added it is easy to forget to add it to json files that configure the libraries (`tests/tlslite-ng.json`, `tlslite-ng-random-subset.json`, possibly others).

Add script that runs in Travis that will verify that all scripts in `scripts/`are mentioned at least once in every json file.

### PR DESCRIPTION
**Pull request by gekios**
I have added the script for issue #156 that verifies that all scripts are in the json files

### Description
Created verify-scripts-json.py script that solves issue #156 

### Motivation and Context
fixes #156 

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [ ] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [ ] new and modified scripts were ran against popular TLS implementations:
  - [ ] OpenSSL
  - [ ] NSS
  - [ ] GnuTLS
- [ ] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/414)

### CODE REVIEW

**Comment by tomato42** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed, 4 unresolved discussions (waiting on @gekios)

---

*[.travis.yml, line 66 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/414#-LFxGvDp7RfmdpJgbFQU:-LFxGvDq3mdCly9RHrB5:b2sfao) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/42b2f56b5e6c850c98b28da4a086b5226a91edb5/.travis.yml#L66)):*
> ```YAML
>   - coverage report -m
>   # check if all scripts are included in the tlslite-ng-random-subset.json file
>   - python tests/verify-scripts-json.py tests/tlslite-ng-random-subset.json
> ```

`tlslite-ng.json` still missing

---

*[Makefile, line 33 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/414#-LFxGyiA8CQdEtBXVdhS:-LFxGyiA8CQdEtBXVdhT:b-dp9ny1) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/42b2f56b5e6c850c98b28da4a086b5226a91edb5/Makefile#L33)):*
> ```Makefile
> 
> test-scripts:
> 	python tests/verify-scripts-json.py tests/tlslite-ng.json
> ```

`tlslite-ng-random-subset.json` missing

---

*[tests/verify-scripts-json.py, line 34 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/414#-LFxH7LZ-_jO_cpdBKfK:-LFxH7LZ-_jO_cpdBKfL:b-z6xj80) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/42b2f56b5e6c850c98b28da4a086b5226a91edb5/tests/verify-scripts-json.py#L34)):*
> ```Python
> 			missing.append(f)
> 	if not missing:
> 		print(" All scripts are in the json file")		
> ```

whitespace at end of line

also, please don't use tabs to indent; all other files in the project use spaces

---

*[tests/verify-scripts-json.py, line 36 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/414#-LFxHmxZ1Wh0R_hJYtPe:-LFxHmxZ1Wh0R_hJYtPf:b-1z5awv) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/42b2f56b5e6c850c98b28da4a086b5226a91edb5/tests/verify-scripts-json.py#L36)):*
> ```Python
> 		print(" All scripts are in the json file")		
> 	else:
> 		print("There are " + str(len(missing)) + " scripts that are missing from " +str(arg)+":")
> ```

please use `str.format()` for string building

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/414)*

**Comment by tomato42** [comment]
Looks like the script found two missing scripts in the json files, I've added them in https://github.com/tomato42/tlsfuzzer/pull/415 please wait with rebase until that PR is merged.

Please [rebase](https://help.github.com/articles/about-git-rebase/) your PR on top of current master branch, then [force push](https://stackoverflow.com/a/10510482/462370) to the same branch as this PR is using.

Do **not** merge the `master` branch to this branch to update it, it will cause failures in Travis CI.

It looks like all those commits introduce just one change, please [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) them together to a single commit.

**Comment by gekios** [comment]
I had added the scripts in the makefile and .yml file but I didn't commit properly. I committed the changes that you requested apart from the .format() one because I had it this way on my initial try but I was getting some compatibility errors on python 2.6 on Travis so I chose to do it this way in order to work. I will check it on my test repo to see if the issues are still there and if not I will add it. According to the script there are 4 scripts missing on tlslite-ng-random-subset.json too. I will go ahead and rebase today after work if all scripts are added.

**Comment by tomato42** [comment]
> some compatibility errors on python 2.6 on Travis

format on Python 2.6 does not support the implicit (`"{} {}".format(val_a, val_b)`) syntax, the references must be explicit (`"{0} {1}".format(val_a, val_b)`)

> According to the script there are 4 scripts missing on tlslite-ng-random-subset.json too.

```
There are 2 scripts that are missing from tests/tlslite-ng-random-subset.json:
test-ffdhe-negotiation.py
test-ssl-death-alert.py
There are 4 scripts that are missing from tests/tlslite-ng.json:
test-ffdhe-negotiation.py
test-ssl-death-alert.py
test-ffdhe-negotiation.py
test-ssl-death-alert.py
```

I think it's because the `missing = []` should be inside the for loop

**Comment by tomato42** [comment]
ok, #415 merged, you can rebase

**Comment by tomato42** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed, 1 unresolved discussion (waiting on @gekios)

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/414)*

**Comment by gekios** [comment]
I fixed the print, as you suggested and rebased.

**Comment by tomato42** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[tests/verify-scripts-json.py, line 34 at r5](https://reviewable.io/reviews/tomato42/tlsfuzzer/414#-LG1o_i0DWMN0S335D3v:-LG1o_i0DWMN0S335D3w:bu2kg6) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/0d3f96be46c8704a1ea9af77920af3535609a1c7/tests/verify-scripts-json.py#L34)):*
> ```Python
>         print(" All scripts are in the json file")
>     else:
>         print("There are {0} scripts that are missing from {1}:".format(str(len(missing)), str(arg)))
> ```

FYI, with format(), the calls to str() are not needed

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/414)*

**Comment by tomato42** [comment]
I still don't see 078ee7b9f9deaf8 in the parents of 0d3f96be46c8, travis passed because the automatically generated github merge commit b04ebcc was the one used for travis run

to rebase, you need to fetch the changes from *this* repo (https://github.com/tomato42/tlsfuzzer.git) and rebase on top of this repo master, not your cloned repo (https://github.com/gekios/tlsfuzzer.git)

in other words, something like this:
```
git remote add tomato42 https://github.com/tomato42/tlsfuzzer.git
git fetch tomato42
git checkout changes-for-issue156
git rebase tomato42/master
```

**Comment by tomato42** [comment]
(also, sorry for insisting so much on the details, but I want to make sure that you understand the workflow with this simple example before you'll have to deal with more complex problems)

**Comment by gekios** [comment]
I am sorry, I misunderstood how rebase is working. Thanks for taking time to clarify things.

**Comment by tomato42** [comment]
Reviewed 1 of 1 files at r6.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/414)*

**Comment by tomato42** [comment]
@gekios awesome, thank you!

**Pull request merged**
