### PR TITLE
utils/ordered_dict: don't use compat code for Python 3.7+

### LINKED ISSUE #706: tlsfuzzer/utils/ordered_dict.py depends on deprecated _dummy_thread module
# Bug Report

## System Information

| Type                     | Version/Name |
| ------------------------ | ------------ |
| Operating System Name    | Fedora |
| Operating System Version | 33 |
| Python version           | Python 3.9.0rc2 |
| tlslite-ng version       | v0.3.9x-1434-g7c6fbf9 |
| tlsfuzzer revision       | 54a1350ae9fa1981062679acb2966e697140c3d1 |

## Problem description

In Python 3.9, the `_dummy_thread` module has been removed:
> _dummy_thread and dummy_threading modules have been removed. These modules were deprecated since Python 3.7 which requires threading support. (Contributed by Victor Stinner in bpo-37312.)

This is causing error in Fedora 33 CI with Python 3.9.0rc2, because that module is used in `tlsfuzzer/utils/ordered_dict.py`.

## Describe how to reproduce the problem

Steps to reproduce the behaviour:

1. podman run -ti registry.gitlab.com/gnutls/build-images:buildenv-fedora33
1. git clone --depth=1 https://gitlab.com/gnutls/gnutls.git
1. cd gnutls && ./bootstrap && ./configure && make && make check

## Expected behaviour

tlsfuzzer tests should pass.

## Include errors or backtraces

```
test-client-compatibility.py:stderr:Traceback (most recent call last):
test-client-compatibility.py:stderr:  File "/builds/gnutls/gnutls/tests/suite/tls-fuzzer/tlsfuzzer/tlsfuzzer/utils/ordered_dict.py", line 8, in <module>
test-client-compatibility.py:stderr:    from thread import get_ident as _get_ident
test-client-compatibility.py:stderr:ModuleNotFoundError: No module named 'thread'
test-client-compatibility.py:stderr:
test-client-compatibility.py:stderr:During handling of the above exception, another exception occurred:
test-client-compatibility.py:stderr:
test-client-compatibility.py:stderr:Traceback (most recent call last):
test-client-compatibility.py:stderr:  File "/builds/gnutls/gnutls/tests/suite/tls-fuzzer/tlsfuzzer/tlsfuzzer/utils/ordered_dict.py", line 11, in <module>
test-client-compatibility.py:stderr:    from dummy_thread import get_ident as _get_ident
test-client-compatibility.py:stderr:ModuleNotFoundError: No module named 'dummy_thread'
test-client-compatibility.py:stderr:
test-client-compatibility.py:stderr:During handling of the above exception, another exception occurred:
test-client-compatibility.py:stderr:
test-client-compatibility.py:stderr:Traceback (most recent call last):
test-client-compatibility.py:stderr:  File "/builds/gnutls/gnutls/tests/suite/tls-fuzzer/tlsfuzzer/scripts/test-client-compatibility.py", line 26, in <module>
test-client-compatibility.py:stderr:    from tlsfuzzer.utils.ordered_dict import OrderedDict
test-client-compatibility.py:stderr:  File "/builds/gnutls/gnutls/tests/suite/tls-fuzzer/tlsfuzzer/tlsfuzzer/utils/ordered_dict.py", line 13, in <module>
test-client-compatibility.py:stderr:    from _dummy_thread import get_ident as _get_ident
test-client-compatibility.py:stderr:ModuleNotFoundError: No module named '_dummy_thread'
ERROR:__main__:test-client-compatibility.py:failure:0.97s:1
```

## Additional context

None.

### PR DESCRIPTION
**Pull request by ueno**
### Description
This makes `tlsfuzzer.utils.ordered_dict.OrderedDict` return `dict` on Python 3.7, as suggested in #706.

### Motivation and Context
Fixes #706.

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] the changes are also reflected in documentation and code comments
- [ ] all new and existing tests pass (see Travis CI results)
- [ ] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [ ] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [ ] new and modified scripts were ran against popular TLS implementations:
  - [ ] OpenSSL
  - [ ] NSS
  - [ ] GnuTLS
- [ ] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/708)

### CODE REVIEW

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/708)* status: all files reviewed, 1 unresolved discussion (waiting on @ueno)

___
*[tlsfuzzer/utils/ordered_dict.py, line 10 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/708#-MJY_7OPDLq19jyds82Y:-MJY_7OQ3wdfqeSXApAU:b-2onrsg) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/0442b33c26c16a7e00fd1739274f5fce3b2669f1/tlsfuzzer/utils/ordered_dict.py#L10)):*
> ```Python
> # Dict keeps insertion order in Python 3.7+:
> # https://mail.python.org/pipermail/python-dev/2017-December/151283.html
> if (sys.version_info.major, sys.version_info.minor) > (3, 6):
> ```

no need to remake the tuple, `(3, 6, 7) > (3, 6) == True` and `(3, 5, 99) < (3, 6) == True`
so it can be just `sys.version_info > (3, 6)`

**Review by ueno — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/708)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @tomato42)

___
*[tlsfuzzer/utils/ordered_dict.py, line 10 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/708#-MJY_7OPDLq19jyds82Y:-MJ_X6Q919ELJ1IjIP3s:b-q5dsyk) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/0442b33c26c16a7e00fd1739274f5fce3b2669f1/tlsfuzzer/utils/ordered_dict.py#L10)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

no need to remake the tuple, `(3, 6, 7) > (3, 6) == True` and `(3, 5, 99) < (3, 6) == True`
so it can be just `sys.version_info > (3, 6)`
</blockquote></details>

That's good; fixed.

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/708)* status: all files reviewed, 1 unresolved discussion (waiting on @ueno)

*[a discussion](https://reviewable.io/reviews/tomato42/tlsfuzzer/708#-MJakctY6joXWy4rUwGf:-MJakct_AumNOZA7QfrR:b-li71xh) (no related file):*
looks like test cases will need slight adjustments for CI to pass

---

**Comment by ueno** [comment]
*[a discussion](https://reviewable.io/reviews/tomato42/tlsfuzzer/708#-MJakctY6joXWy4rUwGf:-MJb2yME95MI995KbIHR:b-felnlw) (no related file):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

looks like test cases will need slight adjustments for CI to pass
</blockquote></details>

What do you expect to fix them: add compatibility with the legacy OrderdDict methods, or align to the dict (and remove test cases for unused OrderdDict methods)?

---

**Review by tomato42 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/708)* status: all files reviewed, 1 unresolved discussion (waiting on @ueno)

*[a discussion](https://reviewable.io/reviews/tomato42/tlsfuzzer/708#-MJakctY6joXWy4rUwGf:-MJbA-f1BN06ueoFtKv1:b-anku9e) (no related file):*
<details><summary><i>Previously, ueno (Daiki Ueno) wrote…</i></summary><blockquote>

What do you expect to fix them: add compatibility with the legacy OrderdDict methods, or align to the dict (and remove test cases for unused OrderdDict methods)?
</blockquote></details>

since the tests check if the code behaves as we need it to, I'd say that we should try to retain as much of them as possible
that being said, methods like `itervalues` and `iterkeys` are unused in tlsfuzzer code, so we can just skip those
fixing `pop()` and `popitem()` test case should be a simple case of not using a name for the argument

---

**Comment by tomato42** [comment]
remember to rebase on top of master, there was a slight issue with py2.6 I had to fix to make the CI functional again

**Review by tomato42 — DISMISSED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/708)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ueno — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/708)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @tomato42)

*[a discussion](https://reviewable.io/reviews/tomato42/tlsfuzzer/708#-MJakctY6joXWy4rUwGf:-MLCE-Cd53aabXYrlrbu:bqqtve9) (no related file):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

since the tests check if the code behaves as we need it to, I'd say that we should try to retain as much of them as possible
that being said, methods like `itervalues` and `iterkeys` are unused in tlsfuzzer code, so we can just skip those
fixing `pop()` and `popitem()` test case should be a simple case of not using a name for the argument
</blockquote></details>

Sorry, I forgot the fact that `OrderedDict` is a subclass of `dict` and `isinstance(d, dict)` cannot be used as a check. I've rewritten it with `type(d) is dict`, which seems to work. Please check again.

---
___
*[tlsfuzzer/utils/ordered_dict.py, line 10 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/708#-MJY_7OPDLq19jyds82Y:-MJ_XKAa7zOUCK8jNIgR:b-896fix) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/0442b33c26c16a7e00fd1739274f5fce3b2669f1/tlsfuzzer/utils/ordered_dict.py#L10)):*
<details><summary><i>Previously, ueno (Daiki Ueno) wrote…</i></summary><blockquote>

That's good; fixed.
</blockquote></details>

Done.

**Comment by tomato42** [comment]
```
test-tls13-shuffled-extentions.py:stderr:Traceback (most recent call last):
test-tls13-shuffled-extentions.py:stderr:  File "scripts/test-tls13-shuffled-extentions.py", line 341, in <module>
test-tls13-shuffled-extentions.py:stderr:    main()
test-tls13-shuffled-extentions.py:stderr:  File "scripts/test-tls13-shuffled-extentions.py", line 180, in main
test-tls13-shuffled-extentions.py:stderr:    rev_ext.update(reversed(ext.items()))
test-tls13-shuffled-extentions.py:stderr:TypeError: 'dict_items' object is not reversible
```
Looks like we can't use the 3.7 implementation of the `dict()`

**Review by tomato42 — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/708)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by tomato42** [comment]
thanks!

**Pull request merged**
