### PR TITLE
test-script for tls1.3 rsa signatures

### LINKED ISSUE #211: TLS 1.3 Certificate Verify signatures (RSA) test script
verify that server is willing to sign the Certificate Verify message with a complete set of signatures supported in TLS 1.3.

ECDSA (#197, #252 ) and EdDSA (#196, #253) signatures will be handled in other scripts

### PR DESCRIPTION
**Pull request by NoName115**
### Description
New test scripts to verify that server will send Certificate Verify message for all supported signatures in TLS 1.3.

### Motivation and Context
fixes #211 

### Checklist
- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL
  - [x] NSS
  - [x] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/410)

### CODE REVIEW

**Comment by NoName115** [comment]
Some tests are excluded in json files, due to an error in tlslite-ng.
Signatures with rsaEncryption should be rejected with handshake alert if the server use rsassa-pss encryption, and the same problem is with rsaEncryption used on server and rsassa-pss on client.

**Comment by NoName115** [comment]
I fixed all the issues, for server that have both rsaEncryption and rsassa-pss certificates, i added -b argument (as both). When the -b argument is present, test do not expect handshake failure.

**Comment by tomato42** [comment]
I've filed https://github.com/tomato42/tlsfuzzer/issues/412 and https://github.com/tomato42/tlslite-ng/issues/279 as related issues

---

Reviewed 3 of 4 files at r3.
Review status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @tomato42 and @NoName115)

---

*[scripts/test-tls13-rsa-signatures.py, line 45 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/410#-LFqxt8WCjH3IhodK0Sn:-LFqxt8X9EwHgqWHQJzZ:bjv4ilr) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/689cb4a97c25b38d03172c6690e654da419f43c7/scripts/test-tls13-rsa-signatures.py#L45)):*
> ```Python
>     print("                (excluding \"sanity\" tests)")
>     print(" -b             if present, test expect that server will sign the")
>     print("                the Certificate Verify message for rsa_ssa")
> ```

"SSA" stands for Signature Scheme with Appendix and it's common between the names of the signature algorithms, see [PKCS#1 v2.2](https://tools.ietf.org/html/rfc8017)

I think you wanted to put "rsa_pss" here

---

*[scripts/test-tls13-rsa-signatures.py, line 46 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/410#-LFqyVpHChSNRoEqBwbc:-LFqyVpHChSNRoEqBwbd:b-bnt8r0) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/689cb4a97c25b38d03172c6690e654da419f43c7/scripts/test-tls13-rsa-signatures.py#L46)):*
> ```Python
>     print(" -b             if present, test expect that server will sign the")
>     print("                the Certificate Verify message for rsa_ssa")
>     print("                encryption, otherwise expect handshake failure")
> ```

I wonder if a clearer message wouldn't be "expect the server to have both the certificate with rsaEncryption key and RSASSA-PSS key"

---

*[scripts/test-tls13-rsa-signatures.py, line 267 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/410#-LFr2Guy67QpY_TNUtsu:-LFr2Guy67QpY_TNUtsv:b-czuiis) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/689cb4a97c25b38d03172c6690e654da419f43c7/scripts/test-tls13-rsa-signatures.py#L267)):*
> ```Python
>     print("Check that server will send the Certificate Verify message")
>     print("for signatures with rsaEncryption.")
>     print("For rsassa-pss certificate, present '-b' argument.\n")
> ```

shouldn't this be "if both rsaEncryption and rsassa-pss certificate are present, add -b argument"?

---

*[scripts/test-tls13-rsassa-signatures.py, line 46 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/410#-LFr2RMcBvruVJU_VHlg:-LFr2RMcBvruVJU_VHlh:b-z9f0j6) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/689cb4a97c25b38d03172c6690e654da419f43c7/scripts/test-tls13-rsassa-signatures.py#L46)):*
> ```Python
>     print(" -b             if present, test expect that server will sign the")
>     print("                the Certificate Verify message for rsaEncyption, ")
>     print("                otherwise expect handshake failure")
> ```

same here, a message about "both" key types present among certificates available to the server would likely be more readable/understandable

---

*[scripts/test-tls13-rsassa-signatures.py, line 268 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/410#-LFr2pf322xhmcDo60zr:-LFr2pf322xhmcDo60zs:b-ganwir) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/689cb4a97c25b38d03172c6690e654da419f43c7/scripts/test-tls13-rsassa-signatures.py#L268)):*
> ```Python
>     print("Check that server will send the Certificate Verify message")
>     print("for signatures with RSASSA-PSS encryption certificate.")
>     print("For rsaEncryption certificate, present '-b' argument.\n")
> ```

same as in the other file

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/410#-:-LFr3LYc9SuDBGI_jHUQ:b1ipqgz)*

**Comment by tomato42** [comment]
Reviewed 1 of 4 files at r3.
Review status: all files reviewed, 5 unresolved discussions (waiting on @NoName115)

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/410)*

**Comment by NoName115** [comment]
Fixed.

**Comment by tomato42** [comment]
Reviewed 2 of 2 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/410)*

**Comment by tomato42** [comment]
script name should be also changed to use "pss": `scripts/test-tls13-rsassa-signatures.py `

**Comment by tomato42** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @NoName115)

---

*[scripts/test-tls13-rsassa-signatures.py, line 154 at r4](https://reviewable.io/reviews/tomato42/tlsfuzzer/410#-LFw_XRw0DbkdJtpSKMb:-LFw_XRx2lJjc26VGSdz:bjjx1se) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/209efc264b51eef213959ad3731281a50fd2931b/scripts/test-tls13-rsassa-signatures.py#L154)):*
> ```Python
> 
>         if test_rsa:
>             node = node.add_child(ClientHelloGenerator(ciphers, extensions=ext))
> ```

duplicated ClientHelloGenerator

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/410)*

**Comment by NoName115** [comment]
Done.

**Comment by tomato42** [comment]
Reviewed 3 of 3 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/410)*

**Comment by tomato42** [comment]
Looks good, thanks!

**Pull request merged**
