### PR TITLE
Add new command node class AddRecordPadding

### LINKED ISSUE #199: TLS1.3 padding support
create a test script for verifying that server supports messages that include padding

see also: https://github.com/tomato42/tlslite-ng/issues/189

### PR DESCRIPTION
**Pull request by ansasaki**
### Description

AddRecordPadding set the callback which returns the length of the
padding to be added to the message in record layer.

It can set the callback as a custom callback provided by the user or
use one of the builtin callbacks.

If no custom callback is provided, but the size of the desired padding
is provided, the callback is set to a simple method which returns the
requested padding size.

If no custom callback is provided, but 'fill' is set to 'True', the
callback is set to a method which returns the maximum padding length
possible.

If nothing is provided, the callback is set to a method which returns
the value 16.

### Motivation and Context

This is required to fix #199 and #384 

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL
  - [x] NSS
  - [x] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/386)

### CODE REVIEW

**Comment by tomato42** [comment]
This pull request **introduces 1 alert** when merging bc93b910a05ab5679294e2c02239b77d938c5187 into 4baabc7f41bf8024713d10e83327b2784015bc4a - [view on lgtm.com](https://lgtm.com/projects/g/tomato42/tlsfuzzer/rev/pr-3f311931805e48ead93fdf96a8fb29280630e2cf)

**new alerts:**

* 1 for Missing call to \_\_init\_\_ during object initialization

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by tomato42** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tlsfuzzer/messages.py, line 162 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChqhoA02xgw98dkkSM:-LChqhoA02xgw98dkkSN:b108epu) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bc93b910a05ab5679294e2c02239b77d938c5187/tlsfuzzer/messages.py#L162)):*
> ```Python
>         callback
>         """
>         self.padding_cb = cb
> ```

call to `super()` missing

---

*[tlsfuzzer/messages.py, line 175 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChmYwFCgjjZHO3P_hf:-LChmYwFCgjjZHO3P_hg:b-36afu5) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bc93b910a05ab5679294e2c02239b77d938c5187/tlsfuzzer/messages.py#L175)):*
> ```Python
>             state.msg_sock.padding_cb = self.padding_cb
> 
>         if not self.padding_cb:
> ```

that series of `if`s is complex but doesn't handle the situation with multiple settings used at the same time (like `size` and `fill` set together)

I think it would be simpler to test those values one by one, (in series of `elif` statements)

or better yet, have the static methods defined as static methods of the class that can be used as ready-to-use callbacks, and for `append_zeroes_cb`, create a factory method that returns a callback, so you'd use it like this in test script:
```
node.add_child(AddRecordPadding(AddRecordPadding.add_sixteen_cb))
```
or
```
node.add_child(AddRecordPadding(AddRecordPadding.add_zeores(30)))
```
(or make the init method do this work)

---

*[tlsfuzzer/messages.py, line 196 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChoN1Z5QIvqq_aP2QP:-LChoN1Z5QIvqq_aP2QQ:bficb4y) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bc93b910a05ab5679294e2c02239b77d938c5187/tlsfuzzer/messages.py#L196)):*
> ```Python
>                 state.msg_sock.padding_cb = _fill_padding_cb
>             else:
>                 def _return_sixteen_cb(length, contenttype, max_padding):
> ```

both this and the `fill_padding_cb` are static, they can be defined outside the method scope

---

*[tlsfuzzer/messages.py, line 204 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChm6UfB6aa2PpVFrGF:-LChm6UfB6aa2PpVFrGG:b7vzly4) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bc93b910a05ab5679294e2c02239b77d938c5187/tlsfuzzer/messages.py#L204)):*
> ```Python
>                         return 16
>                     else:
>                         return max_padding - length
> ```

why not `return min(16, max_padding - length)`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/386)*

**Comment by tomato42** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[tlsfuzzer/messages.py, line 151 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChsd8Y1wXoToa7rPSQ:-LChsd8ZEoVp_Pzqqreu:bcb62mr) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bc93b910a05ab5679294e2c02239b77d938c5187/tlsfuzzer/messages.py#L151)):*
> ```Python
> 
> 
> class AddRecordPadding(Command):
> ```

ok, so this will add a padding callback, how do I remove it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/386)*

**Comment by ansasaki** [comment]
I made the changes before the review. I will make new changes based on the review.

**Comment by tomato42** [comment]
ok, please @mention me when the PR is ready for review

also, please squash fixup commits

**Comment by ansasaki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[tlsfuzzer/messages.py, line 151 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChsd8Y1wXoToa7rPSQ:-LCi5CxQ5SDXf5_ibesJ:bara5n3) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bc93b910a05ab5679294e2c02239b77d938c5187/tlsfuzzer/messages.py#L151)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

ok, so this will add a padding callback, how do I remove it?
</blockquote></details>

I'll change it to accept 'None' as the callback.

---

*[tlsfuzzer/messages.py, line 153 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChYBpaU4PqEyOK0oP9-r1-153:-LCi6CVrBufs_EnnT-3y:b-3nxnyp) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bc93b910a05ab5679294e2c02239b77d938c5187/tlsfuzzer/messages.py#L153)):*
<details><summary><i>Previously, codeclimate[bot] wrote…</i></summary><blockquote>

Line too long (80 > 79 characters)
</blockquote></details>

Addressed in later commits.

---

*[tlsfuzzer/messages.py, line 162 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChqhoA02xgw98dkkSM:-LCi6FoE0c-8yAySoX7S:b-9jv8s1) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bc93b910a05ab5679294e2c02239b77d938c5187/tlsfuzzer/messages.py#L162)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

call to `super()` missing
</blockquote></details>


Addressed in later commits.

---

*[tlsfuzzer/messages.py, line 167 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChYBpaU4PqEyOK0oP9-r1-167:-LCi6Kj45XZAj1LB2Q5U:bqj9ixb) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bc93b910a05ab5679294e2c02239b77d938c5187/tlsfuzzer/messages.py#L167)):*
<details><summary><i>Previously, codeclimate[bot] wrote…</i></summary><blockquote>

Function `process` has a Cognitive Complexity of 15 (exceeds 5 allowed). Consider refactoring.
</blockquote></details>

Addressed in later commits (I hope)

---

*[tlsfuzzer/messages.py, line 175 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChmYwFCgjjZHO3P_hf:-LCi6Pm81Xb0KpmhfYVI:b-j3m2bn) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bc93b910a05ab5679294e2c02239b77d938c5187/tlsfuzzer/messages.py#L175)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

that series of `if`s is complex but doesn't handle the situation with multiple settings used at the same time (like `size` and `fill` set together)

I think it would be simpler to test those values one by one, (in series of `elif` statements)

or better yet, have the static methods defined as static methods of the class that can be used as ready-to-use callbacks, and for `append_zeroes_cb`, create a factory method that returns a callback, so you'd use it like this in test script:
```
node.add_child(AddRecordPadding(AddRecordPadding.add_sixteen_cb))
```
or
```
node.add_child(AddRecordPadding(AddRecordPadding.add_zeores(30)))
```
(or make the init method do this work)
</blockquote></details>

I've changed the constructor to receive only the callback as the argument. And the builtin callbacks are provided as static methods now. For the fixed length padding, a callback factory is provided.

---

*[tlsfuzzer/messages.py, line 196 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChoN1Z5QIvqq_aP2QP:-LCi6wd84tcwCEYhORxx:b-3nxnyp) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bc93b910a05ab5679294e2c02239b77d938c5187/tlsfuzzer/messages.py#L196)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

both this and the `fill_padding_cb` are static, they can be defined outside the method scope
</blockquote></details>

Addressed in later commits.

---

*[tlsfuzzer/messages.py, line 204 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChm6UfB6aa2PpVFrGF:-LCi6ymx8FKsLHo3wLyR:b-3nxnyp) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bc93b910a05ab5679294e2c02239b77d938c5187/tlsfuzzer/messages.py#L204)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why not `return min(16, max_padding - length)`?
</blockquote></details>

Addressed in later commits.

---

*[tlsfuzzer/messages.py, line 203 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChYBpaU4PqEyOK0oP9-r2-203:-LCi72At2qmA3cpG8Q-z:b-18kgx4) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/58d59e79e65a13d90309309d822c289cbc9eda56/tlsfuzzer/messages.py#L203)):*
<details><summary><i>Previously, codeclimate[bot] wrote…</i></summary><blockquote>

Function `process` has a Cognitive Complexity of 6 (exceeds 5 allowed). Consider refactoring.
</blockquote></details>

I hope this is addressed in later commits.

---

*[tlsfuzzer/messages.py, line 169 at r3](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChYBpaU4PqEyOK0oP9-r3-169:-LCi6kbhBwRmJxbjx18A:b-dg1yhk) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/17edcc173cee26365380f64747b6c45da5ddbec5/tlsfuzzer/messages.py#L169)):*
<details><summary><i>Previously, codeclimate[bot] wrote…</i></summary><blockquote>

Continuation line over-indented for visual indent
</blockquote></details>

I'll fix this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/386)*

**Comment by tomato42** [comment]
Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LCi7Q0P4OQUN2XB8N0N:-LCi7Q0Q03LANqirrw4z:b-v9s074) (no related file):*
could you also add an example script that shows how it can be used in practice?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/386)*

**Comment by ansasaki** [comment]
I'll rebase and squash commits.

**Comment by tomato42** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tests/test_tlsfuzzer_messages.py, line 1042 at r4](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LCiLT-E0ESZfPypOvST:-LCiLT-E0ESZfPypOvSU:b8eet3d) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/06593bc81ff8312d80a163bfde89dea672ab36fe/tests/test_tlsfuzzer_messages.py#L1042)):*
> ```Python
> 
>         node = SetPaddingCallback(custom_cb)
>         self.assertIsNotNone(node)
> ```

why is the `custom_cb` necessary for the `__init__` test?

---

*[tests/test_tlsfuzzer_messages.py, line 1122 at r4](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LCiLGpu1-qndTWZqZG8:-LCiLGpu1-qndTWZqZG9:b-8cc9zo) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/06593bc81ff8312d80a163bfde89dea672ab36fe/tests/test_tlsfuzzer_messages.py#L1122)):*
> ```Python
>         unset_node.process(state)
> 
>         self.assertFalse(state.msg_sock.padding_cb)
> ```

`assertIsNone` would probably be a better choice here

---

*[tlsfuzzer/messages.py, line 153 at r1](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChYBpaU4PqEyOK0oP9-r1-153:-LCiKLBPCJ6so8Rr5OLi:b32wtd) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/bc93b910a05ab5679294e2c02239b77d938c5187/tlsfuzzer/messages.py#L153)):*
<details><summary><i>Previously, ansasaki (Anderson Sasaki) wrote…</i></summary><blockquote>

Addressed in later commits.
</blockquote></details>

ok

---

*[tlsfuzzer/messages.py, line 180 at r4](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LCiKngv0tbUb0LWy6Th:-LCiKngv0tbUb0LWy6Ti:b-vkt0nk) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/06593bc81ff8312d80a163bfde89dea672ab36fe/tlsfuzzer/messages.py#L180)):*
> ```Python
> 
>     @staticmethod
>     def no_padding_cb(length, contenttype, max_padding):
> ```

isn't this the same as no callback (`None` set as callback on tlslite-ng level)?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/386)*

**Comment by tomato42** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[tests/test_tlsfuzzer_messages.py, line 1132 at r5](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LCiU6l69IcrWr8GrPBZ:-LCiU6l69IcrWr8GrPB_:b-lfpdln) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/9b417ccfcca67f5dccf6a7780fe1efb3001d51d1/tests/test_tlsfuzzer_messages.py#L1132)):*
> ```Python
>         node.process(state)
> 
>         self.assertRaises(ValueError, state.msg_sock.padding_cb, 20,
> ```

using assertRaises like that makes it much harder to refactor the code, please change it to a context manager:
```python
with self.assertRaises(ValueError):
     state.msg_sock.padding_cb(20, ...)
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/386)*

**Comment by tomato42** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LCi7Q0P4OQUN2XB8N0N:-LCii89VEwPgknry6id6:b13o1pr) (no related file):*
<details><summary><i>Previously, ansasaki (Anderson Sasaki) wrote…</i></summary><blockquote>

Where should I put the example?
</blockquote></details>

in `scripts/`

---

*[tlsfuzzer/messages.py, line 203 at r2](https://reviewable.io/reviews/tomato42/tlsfuzzer/386#-LChYBpaU4PqEyOK0oP9-r2-203:-LCiivOMEG32BkeXL--n:b-jnjka8) ([raw file](https://github.com/tomato42/tlsfuzzer/blob/58d59e79e65a13d90309309d822c289cbc9eda56/tlsfuzzer/messages.py#L203)):*
<details><summary><i>Previously, ansasaki (Anderson Sasaki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you need to click the "ACKNOWLEDGE" button to make it go away from the default view

---


*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/386)*

**Comment by ansasaki** [comment]
@tomato42 Squashed again, ready for review.

**Comment by tomato42** [comment]
Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/386)*

**Comment by tomato42** [comment]
perfect, thank you!

**Pull request merged**
