### PR TITLE
add test-script with invalid key-share extension

### LINKED ISSUE #364: TLS 1.3 key_share omitted
# New test script idea

## What TLS message this idea relates to?

ClientHello

## What TLS extension this idea relates to?

`key_share`, `supported_groups`

## What is the behaviour the test script should test?

Check if TLS 1.3 ClientHello that omits `key_share` extension completely, but does send `supported_groups` is rejected with `missing_extension` alert

also check if a completely empty extension triggers `decode_error`

## Are there scripts that test related functionality?

none

## Additional information

mandatory to implement extensions check

### PR DESCRIPTION
**Pull request by NoName115**
### Description
New test-script fot testing TLS 1.3 communication with omitted or empty key-share extension.

### Motivation and Context
fixes #364 

### Checklist
- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL
  - [x] NSS
  - [x] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

### Additional info
Firstly https://github.com/tomato42/tlslite-ng/pull/310 must be merged for testing.

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/461)

### CODE REVIEW

**Comment by NoName115** [comment]
For NSS, `'key_share extension omitted'` test failed with error in tlsfuzzer
`AssertionError: Unexpected message from peer: Handshake(server_hello)`

For GnuTLS, `  'key_share extension omitted'` test failed with different alert
`AssertionError: Expected alert description "missing_extension" does not match received "internal_error"`

Openssl works fine.

**Comment by NoName115** [comment]
Fixed and rebased.

**Comment by NoName115** [comment]
Fixed.

**Comment by NoName115** [comment]
> why a static key share? #364 is talking only about two cases, key_share being completely empty or omitted...

So what did you mean by "invalid `key_share` and valid `psk_key_exchange_modes`"?
Advertising both, key_share and psk_key_exchange_modes extensions with valid values?

**Comment by tomato42** [comment]
by "invalid" here I meant empty (as in no extension payload at all)

**Comment by NoName115** [comment]
By the current implementation of tlslite-ng in https://github.com/tomato42/tlslite-ng/pull/310, in test `empty key_share extension with valid psk_key exhange modes` we expect missing_extension, as tlslite-ng will send error of missing PSK extension, coz the client advertise `psk_key_exchange_modes` ext.

**Comment by tomato42** [comment]
> By the current implementation of tlslite-ng in [tomato42/tlslite-ng#310](https://github.com/tomato42/tlslite-ng/pull/310), in test `empty key_share extension with valid psk_key exhange modes` we expect missing_extension, as tlslite-ng will send error of missing PSK extension, coz the client advertise `psk_key_exchange_modes` ext.

that's not correct, we should expect `decode_error` as the extension is missing because it is malformed (and presence of `psk_key_exchange_modes` does not mean that the client actually wants to perform PSK key exchange)

**Comment by tomato42** [comment]
looks good, now we need to fix, merge and release tomato42/tlslite-ng#310

also, please retest against common libraries as we've added new test case

**Comment by NoName115** [comment]
Same results, as in my first comment in this PR.

**Comment by tomato42** [comment]
ok, tlslite-ng-0.8.0-alpha19 released

**Comment by NoName115** [comment]
Updated.

**Comment by tomato42** [comment]
Thank you!

**Pull request merged**
