### PR TITLE
Support for post-handshake KeyUpdate

### LINKED ISSUE #323: TLS 1.3 KeyUpdate support
add support for updating encryption keys and IV's

add a script that checks if sending KeyUpdate with update requested causes the other side to respond in kind, verify that the new keys are actually usable (i.e. do the `GET / HTTP/1.0` after KeyUpdate)

depends on https://github.com/tomato42/tlslite-ng/issues/210

### PR DESCRIPTION
**Pull request by NoName115**
### Description
Support for handling KeyUpdate post-handshake msg. This PR adds class for KeyUpdate and class for KeyUpdateGenerator.

### Motivation and Context
https://github.com/tomato42/tlslite-ng/issues/210
fixes #323

### Checklist
- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL openssl/openssl#8188, openssl/openssl#8189
  - [x] NSS [NSS Bug #1526354](https://bugzilla.mozilla.org/show_bug.cgi?id=1526354)
  - [x] GnuTLS [GnuTLS#699](https://gitlab.com/gnutls/gnutls/issues/699)
- [x] required version of tlslite-ng updated in requirements.txt and README.md

### Additional info
Firstly https://github.com/tomato42/tlslite-ng/pull/341 must be merged.

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/501)

### CODE REVIEW

**Comment by NoName115** [comment]
fixed.

**Comment by tomato42** [comment]
This pull request **introduces 1 alert** when merging ba76b1017e8d2e59b5982e5f62f1010325e03c71 into 634647309875e72d281b9e3b091f46bb71eb99c4 - [view on LGTM.com](https://lgtm.com/projects/g/tomato42/tlsfuzzer/rev/pr-36d2e82b94d0a2fd865bd0f4448ecc773dc4f783)

**new alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by NoName115** [comment]
> using mock.Mock() instead of bytearray as the object to be passed in would be more robust, as that would check if the order is preserved

Did you mean, like that:
```
state.msg_sock.calcTLS1_3KeyUpdate_reciever.assert_called_once_with(
                state.cipher, mock.Mock(), mock.Mock())
```
because, this will cause a error
```
AssertionError: Expected call: calcTLS1_3KeyUpdate_reciever(4865, <Mock spec='bytearray' id='139780744042200'>, <Mock spec='bytearray' id='139780743426624'>)
Actual call: calcTLS1_3KeyUpdate_reciever(4865, bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'), bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'))
```

> script that uses those new nodes?

I added test-script. Only https://github.com/tomato42/tlsfuzzer/issues/330 is not included in that test-script yet.

**Comment by tomato42** [comment]
This pull request **introduces 1 alert** when merging 077133f7c9a3f6c3c42b7a50d5c32907cbc468f4 into 634647309875e72d281b9e3b091f46bb71eb99c4 - [view on LGTM.com](https://lgtm.com/projects/g/tomato42/tlsfuzzer/rev/pr-9a1be2562a5fd1d508215f73f293d382f03cebf5)

**new alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by NoName115** [comment]
Failed tests:
**tlslite-ng**
`fragmented keyupdate msg, appdata btw these 2 fragments`
```
Error encountered while processing node ExpectNewSessionTicket() (child: ExpectNewSessionTicket()) with last message being: <tlslite.messages.Message object at 0x7f77dd497e90>
...
AssertionError: Unexpected message from peer: ApplicationData(len=1510)
```

**openSSL**
`large KeyUpdate message`
```
AssertionError: Expected alert description "decode_error" does not match received "illegal_parameter"
```

**GnuTLS**
`app data splited, conversation with KeyUpdate msg`
```
Error encountered while processing node ExpectNewSessionTicket() (child: ExpectNewSessionTicket()) with last message being: None
...
AssertionError: Timeout when waiting for peer message
```
`multiple KeyUpdate messages`
```
Error encountered while processing node <tlsfuzzer.messages.KeyUpdateGenerator object at 0x7fd7d18e4190> (child: <tlsfuzzer.messages.KeyUpdateGenerator object at 0x7fd7d18e4510>) with last message being: <tlslite.messages.KeyUpdate object at 0x7fd7d165bc10>
...
AssertionError: Unexpected closure from peer
```

**NSS**
`invalid message_type - {0}, in KeyUpdate msg` - all tests with invalid msg_type failed
```
AssertionError: Expected alert description "illegal_parameter" does not match received "decode_error"
```
`multiple KeyUpdate messages`
```
Error encountered while processing node <tlsfuzzer.expect.ExpectKeyUpdate object at 0x7f6f25a79d10> (child: <tlsfuzzer.expect.ExpectKeyUpdate object at 0x7f6f25a79d50>) with last message being: <tlslite.messages.Message object at 0x7f6f25a84610>
...
AssertionError: Unexpected message from peer: ApplicationData(len=137)
```
`fragmented keyupdate msg, appdata btw these 2 fragments`
```
Error encountered while processing node ExpectNewSessionTicket() (child: ExpectNewSessionTicket()) with last message being: <tlslite.messages.Message object at 0x7f086736cf90>
...
AssertionError: Unexpected message from peer: ApplicationData(len=137)
```

**Comment by NoName115** [comment]
Fixed.

**Comment by NoName115** [comment]
> ...file a bug and waive in the json file

done, https://github.com/tomato42/tlslite-ng/issues/342

**Comment by tomato42** [comment]
@NoName115 remember to first pull the changes from the branch before starting to work on it!

**Comment by tomato42** [comment]
This pull request **introduces 1 alert** when merging 6be977ac11754fe76b7023938c04532b3752f117 into 42b7595aafe432ed3ecc8e4a393ae2751fa37766 - [view on LGTM.com](https://lgtm.com/projects/g/tomato42/tlsfuzzer/rev/pr-2a7a15c77d9cc588bec72f7da3325e491dcb2aa2)

**new alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ueno** [comment]
@tomato42 I see that the `app data split, conversation with KeyUpdate msg` probe still expects an immediate reply from the server, after sending the first app data. Is it okay to change this to tolerate the behavior that the server only sends the reply right before the next app data?

**Comment by tomato42** [comment]
> @tomato42 I see that the `app data split, conversation with KeyUpdate msg` probe still expects an immediate reply from the server, after sending the first app data. Is it okay to change this to tolerate the behavior that the server delays the reply?

support for the "delaying" server (one that sends the KeyUpdate response with an ApplicationData record) hasn't been added to the script at all

rather than changing the script to tolerate such behaviour, the script should have a switch to expect and verity such behaviour in the server (so that one can use it as a regression test for this feature) – I was thinking about a case with `ExpectNoMessage()`

**Comment by tomato42** [comment]
@inikolcev ok, ready for final review

**Pull request merged**
