### PR TITLE
add test-script for CCS as unexpected message

### LINKED ISSUE #333: TLS 1.3 Change Cipher Spec after handshake
# New test script idea

## What TLS message this idea relates to?

ChangeCipherSpec (CCS)

## What is the behaviour the test script should test?

Send the CCS (unencrypted) after the Finished message, verify the server aborts with `unexpected_message` alert

## Are there scripts that test related functionality?

none

## Additional information

Script to verify that server accepts CCS messages only during handshake

### PR DESCRIPTION
**Pull request by NoName115**
### Motivation and Context
fixes #333 

### Checklist
- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see Travis CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [x] OpenSSL
  - [x] NSS
  - [x] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tomato42/tlsfuzzer/466)

### CODE REVIEW

**Comment by NoName115** [comment]
OpenSSl works fine.
NSS and GnuTLS just ended with incorrect alert description
`AssertionError: Expected alert description "unexpected_message" does not match received "bad_record_mac"`

But tlslite-ng does not work correctly as when `ChangeCipherSpec` message is send, _getMsg method is called with these arguments:
```python
# tlsrecordlayer.py
# line 266
allowedTypes = (ContentType.application_data, ContentType.handshake)
allowedHsTypes = HandshakeType.new_session_ticket
.
.
.
for result in self._getMsg(allowedTypes, allowedHsTypes):
```
So the `ChangeCipherSpec` message is read but ignored, due to `ContentType.handshake`.

I tried to remove `ContentType.handshake` from `allowedTypes` variable, this solved this problem.
With this solution all tests in tlsfuzzer passed but i dont know if this is correct approache.

**Comment by tomato42** [comment]
> OpenSSl works fine.
> NSS and GnuTLS just ended with incorrect alert description
> `AssertionError: Expected alert description "unexpected_message" does not match received "bad_record_mac"`

so they don't check the external type – that's a bug

> So the `ChangeCipherSpec` message is read but ignored, due to `ContentType.handshake`.

that's a bug, the code will need to be more explicit on when the CCS is allowed

and we can't just filter out on new_session_ticket type as there are more Handshake protocol messages acceptable post handshake – key_update and certificate_request (it's just that they are not implemented yet) – the latter of which is also used inside the handshake

> I tried to remove `ContentType.handshake` from `allowedTypes` variable, this solved this problem.
> With this solution all tests in tlsfuzzer passed but i dont know if this is correct approache.

it will break the tlslite-ng client as it won't be able to receive NewSessionTicket messages, but yes, server will be unaffected :)

**Comment by NoName115** [comment]
Bugs reported.
https://gitlab.com/gnutls/gnutls/issues/618
https://bugzilla.mozilla.org/show_bug.cgi?id=1507179
https://github.com/tomato42/tlslite-ng/issues/316

**Comment by NoName115** [comment]
Fixed, just a problem with build-requirements https://github.com/tomato42/tlsfuzzer/pull/478 .

**Comment by NoName115** [comment]
Rebased.

**Comment by tomato42** [comment]
Thanks!

**Pull request merged**
